In [119]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/sudalairajkumar/indian-startup-funding/startup_funding.csv

In [120]:
df= pd.read_csv ('/kaggle/input/datasets/sudalairajkumar/indian-startup-funding/startup_funding.csv')

In [121]:
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

## **Inpecting the data**

In [122]:
# Shape of dataset
print("Rows:", df.shape[0], "Columns:", df.shape[1])

# Info
df.info()

# Missing values
df.isnull().sum()

Rows: 3044 Columns: 10
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     171
SubVertical           936
City  Location        180
Investors Name         24
InvestmentnType         4
Amount in USD         960
Remarks              2625
dtype: int64

**Renaming Column Name**

In [123]:
df.rename(columns={
    'Sr No' : 'Sr_No',
    'Date dd/mm/yyyy': 'Date',
    'Startup Name' : 'StartUp',
    'Industry Vertical' : 'Vertical',
    'City  Location' : 'Location',
    'Investors Name' : 'Investors',
    'InvestmentnType' : 'Round',
    'Amount in USD' : 'Amount'
},inplace = True)

In [124]:
df.columns

Index(['Sr_No', 'Date', 'StartUp', 'Vertical', 'SubVertical', 'Location',
       'Investors', 'Round', 'Amount', 'Remarks'],
      dtype='object')

In [125]:
df.set_index('Sr_No')

,Date,StartUp,Vertical,SubVertical,Location,Investors,Round,Amount,Remarks
Sr_No,,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...
3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

**Correcting the Data Type of Columns**

In [126]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y', errors='coerce')
df['Amount'] = pd.to_numeric(df['Amount'].str.replace(',', ''), errors='coerce')

In [127]:
#df['Amount'] = df['Amount'].str.replace(',','').astype('int64')

- This ValueError occurs because your Amount column contains the text string 'undisclosed', which cannot be converted directly into an integer.
- To fix this, you should use pd.to_numeric() with the errors='coerce' parameter. This will automatically turn non-numeric text like "undisclosed" into NaN (null) values, allowing the rest of the conversion to proceed.
- With errors = 'coerce' If you run into a value that you can't convert, don't crash; just turn it into a NaN

### **Handling the Missing value**

In [128]:
df.isnull().sum()

Sr_No             0
Date              8
StartUp           0
Vertical        171
SubVertical     936
Location        180
Investors        24
Round             4
Amount          979
Remarks        2625
dtype: int64

- Whole row is null:  > df[df.isnull().all(axis=1)]
- At least one null in the row:  > df[df.isnull().any(axis=1)]

In [129]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [Sr_No, Date, StartUp, Vertical, SubVertical, Location, Investors, Round, Amount, Remarks]
Index: []

#### Fixing the inconsistency in the 'Amount' column -

In [130]:
df['Amount'].head()

0    200000000.0
1      8048394.0
2     18358860.0
3      3000000.0
4      1800000.0
Name: Amount, dtype: float64

**Change USD $ to INR (Rs)**

In [131]:
def to_inr(dollar):
    inr = dollar * 94.43  #Convert USD to INR
    return inr/10000000   #Converting INR to Carores

In [132]:
df['Amount']=df['Amount'].apply(to_inr)

In [133]:
df['Amount'].head()

0    1888.600000
1      76.000985
2     173.362715
3      28.329000
4      16.997400
Name: Amount, dtype: float64

In [134]:
#Filling the missing value in the Amount column 
mean= df['Amount'].mean()
median = df['Amount']. median()

print(f'Mean = {mean}')
print(f'Median = {median}')

Mean = 174.0335199282467
Median = 16.0531

Mean (174.03) is significantly higher than your Median (16.05). This usually means your 'Amount' column has outliers

In [135]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df['Amount'].quantile(0.25)
Q3 = df['Amount'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds (standard is 1.5 * IQR)
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter the DataFrame to remove outliers
df_cleaned = df[(df['Amount'] >= lower_bound) & (df['Amount'] <= upper_bound)]

print(f"Old shape: {df.shape}")
print(f"New shape: {df_cleaned.shape}")

Old shape: (3044, 10)
New shape: (1782, 10)

- Row count dropped from 3044 to 1782. This happened because the filter (df['Amount'] >= lower_bound) automatically excludes rows where the amount is NaN.

In [136]:
new_mean = df_cleaned['Amount'].mean()
new_median = df_cleaned['Amount'].median()

print(f'New Mean = {new_mean}')
print(f'New Median = {new_median}')

New Mean = 29.835263762530563
New Median = 9.443

Even after removing outliers, your Mean (29.8) is still about 3 times higher than your Median (9.44). This suggests your data is still "right-skewed

In [137]:
df.isnull().sum()

Sr_No             0
Date              8
StartUp           0
Vertical        171
SubVertical     936
Location        180
Investors        24
Round             4
Amount          979
Remarks        2625
dtype: int64

In [138]:
df['Amount'] = df['Amount'].fillna(new_median)

- Using the Median to fill 939 rows (about 30% of your data) is a common practice, but it comes with a trade-off you should consider.
- Filling nearly 1,000 rows with the exact same number (9.44) will create a huge "spike" in your data. This can make your correlations look stronger or weaker than they actually are because you've artificially reduced the variety in the 'Amount' column.

In [139]:
# Final clean-up after filling NaNs
df = df[(df['Amount'] >= lower_bound) & (df['Amount'] <= upper_bound)]

In [140]:
# Checking the misisng value percentage -
df.isnull().sum()/len(df) *100

Sr_No           0.000000
Date            0.289750
StartUp         0.000000
Vertical        5.541470
SubVertical    30.785947
Location        5.831221
Investors       0.833032
Round           0.108656
Amount          0.000000
Remarks        87.576965
dtype: float64

In [141]:
# Remark has more that 80 perc of missing value --> So we ca remove them 
df = df.drop(columns=['Remarks'])

In [142]:
df[df['Vertical'].isnull()]

,Sr_No,Date,StartUp,Vertical,SubVertical,Location,Investors,Round,Amount
2873,2874,2015-03-02,TrulyMadly.com,NaN,NaN,NaN,"Helion Venture Partners, Kae Capital",Private Equity,51.936500
2874,2875,2015-03-02,InstaLively,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,1.133160
2875,2876,2015-03-03,Vserv,NaN,NaN,NaN,"Maverick Capital, IDG Ventures India",Private Equity,141.645000
2876,2877,2015-03-03,Intruo.com,NaN,NaN,NaN,"Ashutosh Lawania, Alok Goel & others",Seed Funding,9.443000
2877,2878,2015-03-05,Niffler,NaN,NaN,NaN,SAIF Partners,Seed Funding,9.443000
...,...,...,...,...,...,...,...,...,...
3039,3040,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,42.493500
3040,3041,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,7.790475
3041,3042,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,14.164500
3042,3043,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,9.443000
3043,3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.322020

In [143]:
df[df['Location'].isnull()]

,Sr_No,Date,StartUp,Vertical,SubVertical,Location,Investors,Round,Amount
338,339,2018-03-20,One Labs,Consumer Internet,Consumer Technology and Artificial Intelligenc...,NaN,Micromax Informatics Ltd,Private Equity,9.443000
1600,1601,2016-06-13,Matrubharti,Consumer Internet,e-Book Publisher,NaN,Viridian Capital,Seed Funding,0.283290
1765,1766,2016-04-12,Indi.com,Consumer Internet,Video Social Network,NaN,Anil Kapoor,Seed Funding,9.443000
1811,1812,2016-04-27,CareonGO,Consumer Internet,Online Pharmacy,NaN,"Farooq Oomerbhoy, Anupam Mittal, Anand Mittal,...",Seed Funding,9.443000
1891,1892,2016-03-23,HashLearn,Consumer Internet,Mobile based private tutoring services,NaN,"Bhavish Aggarwal, Binny Bansal,\\xc2\\xa0 Raja...",Seed Funding,9.443000
...,...,...,...,...,...,...,...,...,...
3039,3040,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,42.493500
3040,3041,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,7.790475
3041,3042,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,14.164500
3042,3043,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,9.443000
3043,3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.322020

In [144]:
df= df.dropna(subset=['Vertical','SubVertical','Location'], how= 'all')

In [145]:
# Filling the missing value
# 'SubVertical' (fillng it with unknown)
df['SubVertical'] = df['SubVertical'].fillna("Unknown")

In [146]:
#Filling the Investors columns
df['Investors'] = df['Investors'].fillna('Undisclosed')

In [147]:
# Checking the misisng value percentage -
df.isnull().sum()

Sr_No          0
Date           6
StartUp        0
Vertical       0
SubVertical    0
Location       8
Investors      0
Round          3
Amount         0
dtype: int64

In [148]:
df = df.dropna(subset = ['Date', 'StartUp', 'Vertical', 'Location', 'Investors', 'Round','Amount'])#

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2591 entries, 1 to 2872
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sr_No        2591 non-null   int64
 1   Date         2591 non-null   datetime64[ns]
 2   StartUp      2591 non-null   object
 3   Vertical     2591 non-null   object
 4   SubVertical  2591 non-null   object
 5   Location     2591 non-null   object
 6   Investors    2591 non-null   object
 7   Round        2591 non-null   object
 8   Amount       2591 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 202.4+ KB

In [150]:
#Checking for duplicate rows
duplicates = df.duplicated().sum()
print(f'The Dataframe has {duplicates} no. rows ')

The Dataframe has 0 no. rows

#### **Fixing the inconsistency in the 'StartUp' column -**

In [151]:
#Getting all the startup name 
df['StartUp'].unique().shape

(2181,)

In [152]:
df['StartUp'].unique().tolist()

['Shuttl',
 'Mamaearth',
 'https://www.wealthbucket.in/',
 'Fashor',
 'Pando',
 'Ecozen',
 'Healthians',
 'InCred',
 'Trell',
 'Misters',
 'Sunstone Eduversity Pvt. Ltd',
 'Burger Singh',
 'Aye Finance',
 'SuperGaming',
 'eBikeGo',
 'Medikabazaar',
 'The Man Company',
 'FPL Technologies',
 'Cashflo',
 'Digital F5',
 '3rdFlix',
 '75F',
 'Myelin Foundry',
 'Atomberg Technology',
 'Vyapar App',
 'Progcap',
 'MyPetrolPump',
 'Cars24',
 'Lo! Foods',
 'INDwealth',
 'HungerBox',
 'AdmitKard',
 'Mishry Reviews',
 'RenewBuy',
 'Atlan',
 'WizCounsel',
 'Ola Cabs',
 'Daalchini Technologies',
 'Ezyhaul',
 'Indus OS',
 'HealthAssure',
 'House of Msasaba',
 'Board Infinity',
 'Bira91',
 'Avail Finance',
 'Agara Labs',
 'Pratilipi',
 'Bolo App',
 'OkCredit',
 'Vogo Automotive Pvt. Ltd.',
 'Leegality',
 'Ola Electric',
 'Saahas Zero Waste',
 'StyleDotMe',
 'GlowRoad',
 'Medlife',
 'Kabadiwala',
 'Tripoto',
 'Azah',
 'Setu',
 'Toppr',
 'Craftsvilla',
 'Unacademy',
 'My Healthcare',
 'KrazyBee',
 'Increff',
 'FleetX',
 'NanoClean Global',
 'Samunnati Financial Intermediation & Services Pvt. Ltd',
 'Manch',
 'Guiddoo',
 'Career Anna',
 'Nagpur Wholesale',
 'ShopKirana',
 'BuildSupply',
 'GoDesi',
 'Mobile Premier League',
 'A&R Bon Vivants',
 'Blackbuck',
 'MilkBAsket',
 'DriveU',
 'CleanseCar',
 'HealthifyMe',
 'Genius Corner',
 'Skillbox',
 'Signzy',
 'Roposo',
 'Northmist',
 'Origo Commodities India Pvt. Ltd',
 'Grover Zampa',
 'Droom',
 'Innov8',
 'LetsTransport',
 'Daily hunt',
 '3HCare',
 'HappyGoEasy',
 'Mad Street Den',
 'MamaEarth',
 'Pharmeasy',
 'Upwards',
 'dishq',
 'HealthFin',
 'Samosa Labs',
 'ZiffyHomes',
 'My OmNamo',
 'MakeMyTrip',
 'Hansel io',
 'Metro Bikes',
 'quizizz',
 'Happy EMI',
 'Inthree',
 'Observe AI',
 'Enakshi',
 'EazyDiner',
 'Finzy',
 'RawPressery',
 'Pi Ventures',
 'Revv',
 'ZestMoney',
 'Shubh Loans',
 'MyUpchar',
 'Narvar',
 'Leena AI',
 'Biryani By Kilo',
 'Anchanto',
 'zippserv',
 'Groww',
 'Avenue Growth',
 'iNICU',
 'Kinara Capital',
 'Shop 101',
 'Sambandh',
 '19th mile',
 '5th Vital',
 'MEngage',
 'The Ken',
 'HousingMan',
 'PaySense',
 'Yulu Bikes',
 'VTION',
 'Log9 Materials',
 'kidovators',
 'Black Soil',
 'iqlect',
 'Entropik',
 'Bitla Software',
 'TheCapitalNet',
 'Healthsignz',
 'CoinTribe',
 'Digiconectt',
 'Kashmir Box',
 'Crowdera',
 'Zoctr',
 'Meesho',
 'Theranosis',
 'Alpha Capital',
 'eshakti',
 'Daily Ninja',
 'NirogStreet',
 'Nivesh',
 'What\\\\xe2\\\\x80\\\\x99s Up Life',
 'HomeLane',
 'Network Intelligence',
 'Elucidata',
 'Chrysalis',
 'RentSher',
 'Drip capital',
 'WickedRide',
 'HipBar',
 'Sqqrl',
 'Paytm',
 'Sigtuple',
 'Wow Express',
 'Front Desk AI',
 'Edureka',
 'Numeroseven',
 'OpenTap',
 'Disprz',
 'PaisaDukan',
 'i3sysytems',
 'Earth Food',
 'mfine',
 'Rocketium',
 'MilkBasket',
 'Vola',
 'Cashkumar',
 'Edyoo',
 'Aashiyaan',
 'Smartivity',
 'Bonphulapl',
 'Acko',
 'HWell24',
 'Toffee',
 'Tonetag',
 'Events High',
 'Stellaps',
 'Credright',
 'Fitternity',
 'Synctag',
 'Benepik',
 'IndigoLearn',
 'Vedantu',
 'Kaleidofin',
 'Pipabella',
 'Elemential',
 'Kriger Campus',
 'Loanzen',
 'TravelTriangle',
 'Letsmd',
 'AyeFinance',
 'mintifi',
 'icanstay',
 'Pregbuddy',
 'Lenskart',
 'mamaearth',
 'Fyle Technologies',
 'Visit',
 'Doxper',
 'Nykaa',
 'Mihuru',
 'Trip shelf',
 'POPxo',
 'RailYatri',
 '1mg',
 'Rubique',
 'Samco',
 'MyLoanCare',
 'PharmEasy',
 'Buddy4studdy',
 'Urban Ladder',
 'Kuvera',
 'Gramophone',
 'Wellthy',
 'MedGenome',
 'Finova Capital',
 'Hotelogix',
 'Livehealth',
 'Ad2pro',
 'Coverfox',
 'Magicpin',
 'HealthCare',
 'Stumagz',
 'AvailFinance',
 'Fingerlix',
 'Karma Healthcare',
 'Zappfresh',
 'CustomerSucessBox',
 'GigIndia',
 'Chargebee',
 'i2i Funding',
 'Slang Labs',
 'UrbanPiper',
 'Cash Suvidha',
 'Roadcast',
 'Smartcoin',
 'The Print',
 'Fynd',
 'CollegeDekho',
 'Foodmemories',
 'Healthi',
 'healthifyme',
 'MedTel',
 'Rupeek',
 'WebEngage',
 'Wydr',
 'Cashify',
 'holachef',
 'Awaaz De',
 'IMAX Program',
 'Littlemore',
 'Shirsa Labs',
 'MoneyOnMobile',
 'PetSutra',
 'Infibeam',
 'happay',
 'Fincash',
 'Agricxlab',
 'The Healthy Billions',
 'HighRadius',
 'Avishkaar Box',
 'Planys Technologies',
 'Lollypop',
 'Trilyo',
 'Credy',
 'Predible Health',
 'CleverTap',
 'EarlySalary',
 'WOTU',
 'DAAKI',
 'Lendingkart',
 'Kinsane Entertainment Inc',
 'Tapzo',
 'Appario Retail Pvt Ltd.',
 'Kuants',
 'Streak',
 'Rubix',
 'ShareChat',
 'Paperflite',
 'Skillate',
 'OptaCredit',
 'AEON Learning',
 'Milkbasket',
 'Rao IIT Academy',
 'Glassic',
 'GreyAtom',
 'Axio',
 'eKincare',
 'The Wedding Brigade',
 'PeeSafe',
 'Scapic',
 'CureFit',
 'iNurture',
 'Strata Enviro',
 'Dunzo',
 'HandyTrain',
 'Mobycy',
 'Fintobox',
 'Mswipe',
 'The Label Life',
 'Cygnus Hospitals',
 'eShakti',
 'Inshorts',
 'Vahdam Tea',
 'Logic Roots',
 'Project Mudra',
 'Furlenco',
 'I Can Stay',
 'Fracktal Works',
 'Simility',
 'Shopholix',
 'DocsApp',
 'Capita World',
 'Tea Box',
 'Transversal Technologies',
 'Curofy',
 'WeDoSky',
 'Purplle',
 'Sky Met Weather',
 'Springboard',
 'Peel Works',
 '9Stacks',
 'Your Quote',
 'EasyEcom',
 'IGP.com',
 'Specsmakers',
 'Garage On Road',
 'Foyr.com',
 'Prest Loans',
 'AadharAPI.com',
 'FreshBoxx',
 'Vagupu',
 'HalaPlay',
 'Kalpnik Technologies',
 'Hevo Data',
 'Smart Karma',
 'Leverage Edu',
 'Crayon Data',
 'DocTalk',
 'CoveIoT',
 'TalentEdge',
 'Fisdom',
 'FarmLink',
 'OpenApp',
 'NoPaperForms',
 'Tilite Technologies Pvt. Ltd',
 'Mobiliz AR',
 'Happily Unmarried',
 'Universal Sportsbiz Pvt. Ltd',
 'Hungry Foal',
 'Active AI',
 'Sumeru',
 'ElderAid Wellness',
 'Omnia Information',
 'Josh Talks',
 'Reniso',
 'Kanhaiya',
 'Perspectico',
 'ONN Bikes',
 'Rapido',
 'Heckyl',
 'Nuvepro',
 'RedBook',
 'Credit Mate',
 'MiStay',
 'WittyFeed',
 'IDG Ventures',
 'TempGo',
 'ERA',
 'Smaaash',
 'Chumbak',
 'FR8',
 'MobieFit',
 'Stanza Living',
 'ChqBook',
 'HomeCapital',
 'Elanic',
 'CollPoll',
 'Little Black Book',
 'Oorjan',
 'Zefo',
 'Yaantra',
 'Farm Taaza',
 'Drivezy',
 'Slice Pay',
 'Agrowave',
 'MyGubbi',
 'IBSFintech',
 'Letsservice',
 'OneStepUp',
 'ThirdWatch',
 'Parallel Dots',
 'Easy Diner',
 'StanPlus',
 'UCLID',
 'Gapoon',
 'Chaayos',
 'Renew Buy',
 'Bank Bazaar',
 'Hasura',
 'BlackBuck',
 'LenDen Club',
 'RAW Pressery',
 'Cashe',
 'Park Easy',
 'TagBox',
 'FYRE',
 'ZipLoan',
 'Skillenza',
 'Chevon',
 'PropStory',
 'SpotDraft',
 'Big Basket',
 'OfBusiness',
 'Olly Credit',
 'CashFree',
 'GoldFarm',
 'NetMeds',
 'Aahaa Stores',
 'MFine',
 'Canvera',
 'PrimaryIO',
 'Nest Education',
 'Lending Kart',
 'GoFro',
 'OncoStem',
 'Credit Vidya',
 'Tails Life',
 'Early Salary',
 'Seniority',
 'AYE Finance',
 'Farmizen',
 'Call Health',
 'Sattviko',
 'Tonbo Imaging',
 'Get My Parking',
 'Glowroad',
 'OYO Rooms',
 'Heterogenous',
 'Gurukul',
 'WheelStreet',
 'Xprep',
 'The Moms Co',
 'Noticeboard',
 'HWell24 Plus',
 'SaveBC',
 'Gaming Monk',
 '91SpringBoard',
 'Homergize',
 'Yatra.com',
 'Ace Turtle',
 'Vogo',
 'Synup',
 'Tinmen',
 'Cropin',
 'Sportobuddy',
 'Credifiable',
 'Inclov',
 'Multibhashi',
 'Transerve',
 'Fashalot',
 'Pitstop',
 'GoChoppers',
 'Aadyah',
 'TouchKin',
 'Ethinos',
 'Zepo',
 'Click2Clinic',
 'SpeedBox',
 'Skill Connect',
 'Chai Point',
 'Lime Tray',
 'CoutLoot',
 'Box My Space',
 'Curatio',
 'New Castle Technologies',
 'My Forex Eye',
 'TruxApp',
 'CroFarm',
 'DoodhWala',
 'Stayabode',
 'Moong Labs',
 'Sports Flashes',
 'Digilend',
 'KNAB Finance',
 'Get Simpl',
 'Rootefy',
 'Uniphore',
 'Cerebroz',
 'Flochat',
 'EasyGov',
 'Milk Basket',
 'Bombay Shaving Company',
 'Awign',
 'Indiez',
 'Ezetap',
 'Ink Monk',
 'Medinfi',
 'Mobikon',
 'Fieldassist',
 'Billion Loans',
 'Ecolibriumenergy',
 'Jumbotail',
 'Moglix',
 'Timesaverz',
 'Minjar',
 'MyCity4kids',
 'Clip App',
 'Upwardly.in',
 'Autorox.co',
 'Fabogo',
 'Flickstree',
 'Design Cafe',
 'Innoviti',
 'VDeliver',
 'Bottr.me',
 'Arcatron',
 'QwikSpec',
 'Vayana',
 'MObiquest',
 'Ambee',
 'Ideal Insurance',
 'Hypernova Interactive',
 'Rentomojo',
 'AirCTO',
 'Playablo',
 'Trupay',
 'Brick2Wall',
 'FableStreet',
 'Monsoon Fintech',
 'MonkeyBox',
 'Creator\\\\xe2\\\\x80\\\\x99s Gurukul',
 'ThinkerBell',
 'Jhakaas',
 'BigStylist',
 'Gympik.com',
 'Tripeur',
 'RentOnGo',
 'MaxMyWealth',
 'Spinny',
 'Healthbuds',
 'Ftcash',
 'BHIVE Workspace',
 'wayForward',
 'GyanDhan',
 'GrowFitter',
 'Stratfit',
 'Multiplier Solutions',
 'ABI Health',
 'Stockal',
 'Guidoo',
 'eSahai.in',
 'Loanmeet',
 'LendingKart',
 'Boxx.ai',
 'PeeSafe.in',
 'Vista Rooms',
 'CoverFox',
 'HyperTrack',
 'Goodera',
 'Digit',
 'Vanitycask',
 'MrNeeds',
 'MoneyTap',
 'Goodbox',
 'PortDesk',
 'EdgeFx',
 'HealthIntel',
 'Unbxd',
 'DarwinBox',
 'ForeverShop',
 'Insider.in',
 'Grow Fit',
 'Fabulyst',
 'OneAssist',
 'Julia Computing',
 'Kissht',
 'Explore Life traveling',
 'Loantap',
 'Voxweb',
 'HUG Innovations',
 'V Resorts',
 'Stashfin',
 'Formcept',
 'Spares Hub',
 'FiTraQ',
 'Niki.ai',
 'Fitpass',
 'ZingHR',
 'Tagos Design',
 'Power2SME',
 'Innovapptive',
 '4tigo',
 'SMECorner',
 'ZippServe',
 'HealthMir',
 'Uactive',
 'i-lend',
 'Good Methods Global',
 'Balance App',
 'YepMe',
 'Nightstay',
 'Devourin',
 'MyGreens',
 'Curie Labs',
 'Uncanny Vision',
 'Sequretek',
 'Lucideus',
 'Vidooly',
 'Shopclues',
 'Fourth Ambit',
 'Chymera VR',
 'Book My Diamond',
 'ION Energy',
 'Legal Raasta',
 'Log 9 Materials',
 'Remit Guru',
 'Aequm',
 'Zapty',
 'Vernacular.ai',
 'Telr',
 'Genie',
 'Paysense',
 'The Good Life',
 'PumpKart',
 'EzCred',
 'HealthSutra',
 'ZipGrid',
 'TravelSpice',
 'Box8',
 'GenNext Students',
 'WhatsLoan',
 'Cube Consumer Services',
 'Wowflux',
 'Collateral Medical',
 'Loadshare',
 'SimpliLend',
 'Supr Daily',
 'SastaSundar',
 'Eruditus',
 'TestBook',
 'Tyre Express',
 'SmartCoin',
 'WayCool',
 'Perfios',
 'Whatfix',
 'ElastiRun',
 'Trukky',
 'Konsult App',
 'Credit Sudhaar',
 'DataWeave',
 'Mech Mocha',
 'Startup Buddy',
 'QorQI',
 'Twenty Two Motors',
 'WonderChef',
 'FastFox',
 'Omnify',
 'Capital Float',
 'Ninjacart',
 'MergerWare',
 'Clovia',
 'Emiza',
 'HackerEarth',
 'Squadrun',
 'ScoutMyTrip',
 'SafetyKart',
 'WeAreHolidays',
 'Myly',
 'CrediHealth',
 'Navia Life Care',
 'Raw Pressery',
 'Snackible',
 'Be U Salons',
 'Simulanis',
 'Innefu Security Consulting',
 'Whodat',
 'Absentia VR',
 'IOTrek',
 'HolaChef',
 'Wooplr',
 'Video Ken',
 'Faasos',
 'Niramai',
 'The Office Pass',
 'UrbanClap',
 'Myra',
 'Flytxt',
 'Howdy Ventures',
 'StalkBuyLove',
 'ZipGo',
 'Scootsy',
 'Autobix',
 'eShiksha',
 'Sepalika',
 'Mintwalk',
 'Qriyo',
 'Belong',
 'Seenit',
 'Paalak',
 'Celes Care',
 'Karomi',
 'Red Carpet',
 'Kreate Konnect',
 'CreditMantri',
 'Lets Endorse',
 'Tydy',
 'Nactus',
 'Oho Shop',
 'Emojifi',
 'Juno Clinic',
 'Summerlabel',
 'PickMe',
 'Agrostar',
 'Zapr',
 'Data Resolve',
 'Book Servicing',
 'Blowhorn',
 'Rivigo',
 'PipeCandy',
 'Parentune',
 'AppBrowzer',
 'MagicBricks',
 'PeeBuddy',
 'iOrderFresh',
 'Lavelle Networks',
 'PropertyShare',
 'MyDermacy',
 'LatestOne',
 'Frapperz',
 'mPaani',
 'ShilpMIS',
 'Fitso',
 'FarMart',
 'Airpay',
 'MyGlamm',
 'The Mons Co.',
 'Haqdarshak',
 'Ixigo',
 'Bizom',
 'BabyonBoard',
 'Sport Flashes',
 'Wigzo',
 'DoneThing',
 'Zapyle',
 'Ithaka',
 'perpule',
 'Byju\\\\xe2\\\\x80\\\\x99s',
 'Licious',
 'Emflux Motors',
 'Klinic App',
 'Oriano Solar',
 'BigBasket',
 'Rooter',
 'FalconBrick',
 'Clodura',
 'Stockroom.io',
 'iManageMyHotel',
 'Inner Hour',
 'Travel Triangle',
 'Wandertrails',
 'Zenatix',
 'MindYourFleet',
 'Edurev',
 'Voonik',
 '1Crowd',
 '48East',
 'Redesyn',
 'Flutura',
 'Wassup',
 'Better Mortgage',
 'Nurturey',
 'Fyle',
 'GoBumpr',
 'Connaizen',
 'AirZaar',
 'Truebil',
 'YourStory',
 'Imaginate',
 'Aisle',
 'TownScript',
 'Leopetra',
 'Blood n Care',
 'True Balance',
 'Vebbler',
 'Lets Reap',
 'Oglas',
 'Staydobe',
 'Johari Shop',
 'NeoStencil',
 'TaxSutra',
 'TempoGo',
 'GoFynd',
 'Vow Car Clinic',
 'LearnTron',
 'MobiDent',
 'Yostra',
 'Leap India',
 'Intelligence Node',
 'Securens',
 'Loan Frame',
 'DriveSkool',
 'LensKart',
 'InstaOffice',
 'Hansel.io',
 'Square Yards',
 'Roambee',
 'PaisaWapas',
 'iService',
 'SecururAX',
 'Leadburg',
 'ZoloStays',
 'Oi Media',
 'HipCouch',
 'Curiositi',
 'TinyStep',
 'Ketchupp',
 'Hoopy',
 'Ezytruk',
 'Kratikal',
 'Direct Create',
 'Vahdam Teas',
 'Qwikspec',
 'PParke',
 'Weddingz.in',
 'Native Special',
 'Fitnapp',
 'Ethosh',
 'MessaGif',
 'SmartHi',
 'CRON Systems',
 'CueMath',
 'ChipperSage',
 'SelectJobs',
 'Khel Now',
 'NowFloats',
 'Lets Transport',
 'BetaOut',
 'Wishberry',
 'RML Agtech',
 'LoyaltyPrime',
 'InstaSafe',
 '99Games',
 'AirMed Labs',
 '99PerHour',
 'Kochi Post',
 'Intuit Things',
 'Cloudrino',
 'FabX',
 'Maptags',
 'YOLO Health',
 'Heads Up For Tails',
 'Register My Marriage',
 'SidQam',
 'India Lends',
 'Slide App',
 'Badiyajobs',
 'Streo',
 'TYGR',
 'Mr Hot Foods',
 'UrDoorStep',
 'Diro Labs',
 'THB',
 'LookAtMe',
 'Netree',
 'BookEventz',
 'Tailslife',
 'WealthApp',
 'Vehico',
 'Zest Money',
 'GoMechanic',
 'Stalk Buy Love',
 'Wittyparot',
 'NeuroEquilibrium',
 'Xseed Education',
 'Rupaiya Exchange',
 'Doctor Insta',
 'Fresh Food Concepts',
 'Indifi',
 'GoComet',
 'Fitmein',
 'Qacco',
 'MoEngage',
 'Ten3t Health',
 'Trading Bells',
 'SERV\\\\xe2\\\\x80\\\\x99D',
 'IdeaForge',
 'Pocket Aces',
 'TripShelf',
 'NoBroker',
 'VivoCarat',
 'Tiyo',
 'Zoomcar',
 'BYJU\\\\xe2\\\\x80\\\\x99s',
 'The BlueBook',
 'Vegetall',
 'Innoplexus',
 'Mindler',
 'MCaffeine',
 'enKast',
 'MyAdvo',
 'Asocon',
 'LexComply',
 'The Postbox',
 'Pandorum Technologies',
 'Dekkho',
 'Shadowfox',
 'ShopX',
 'Healthifyme',
 'LetsMD',
 'Justbooks',
 'InstantPay',
 'PickMyLaundry',
 'LaundryAnna',
 'Zarget',
 'DoSelect',
 'EasyPolicy',
 'Browntape',
 'Connect India',
 'Corseco',
 'vImmune',
 'The Gourmet Jar',
 'Medzin',
 'Bizongo',
 'JustRide',
 'IIM Jobs',
 'GolfLAN',
 'Yottaasys',
 'Tone Tag',
 'Life in Control',
 'Active.ai',
 'ElasticRun',
 'PlaySimple',
 'Stasis Labs',
 'Scienaptic',
 'Koovs',
 'Lawrato',
 'Trip Tap Toe',
 'Pictor Imaging',
 'GramCover',
 'AerMed',
 'WorkIndia',
 'Bats on delivery',
 'numberz.in',
 'Housing.com',
 'Awesummly',
 'VoLT',
 'Vymo',
 'ShubhLoans',
 'Noddapp',
 'Infisecure',
 'Udaan',
 'FroyoFit',
 'Betterplace',
 'UClean',
 'Servify',
 'Hubilo',
 'FunOnGo',
 '121Policy',
 'TapChief',
 'Kloseby',
 'WholeSaleBox',
 'Crossahead',
 'Affordplan',
 'ShopsUp',
 'Indofash',
 'Entropika',
 'MarianaIQ',
 'Chai Thela',
 'Interviewpad',
 'Math Buddy',
 'Pulse',
 'Carcrew.in',
 'MeraKisan',
 'Mystifly',
 'HelpChat',
 'World Art Community',
 'Giftxoxo',
 'Bharat Bazaar',
 'GOQii',
 'India Gifts Portal',
 ...]

In [153]:
#By manual assessment we get the inconsistency in startup names ----> Resolving that 
df['StartUp'] = df['StartUp'].str.replace(r'\\\\xe2\\\\x80\\\\x99', "'", regex=True).str.replace(r'\\\\xe2\\\\x80\\\\x9d', '"', regex=True).str.replace(r'\\\\x[a-f0-9]{2}', '', regex=True).str.replace('https://www.wealthbucket.in/','Wealth Bucket').str.replace(r'\s+', ' ', regex=True).str.strip()
df['StartUp'] = df['StartUp'].str.title().str.strip()

In [154]:
df['StartUp'].unique().tolist()

['Shuttl',
 'Mamaearth',
 'Wealth Bucket',
 'Fashor',
 'Pando',
 'Ecozen',
 'Healthians',
 'Incred',
 'Trell',
 'Misters',
 'Sunstone Eduversity Pvt. Ltd',
 'Burger Singh',
 'Aye Finance',
 'Supergaming',
 'Ebikego',
 'Medikabazaar',
 'The Man Company',
 'Fpl Technologies',
 'Cashflo',
 'Digital F5',
 '3Rdflix',
 '75F',
 'Myelin Foundry',
 'Atomberg Technology',
 'Vyapar App',
 'Progcap',
 'Mypetrolpump',
 'Cars24',
 'Lo! Foods',
 'Indwealth',
 'Hungerbox',
 'Admitkard',
 'Mishry Reviews',
 'Renewbuy',
 'Atlan',
 'Wizcounsel',
 'Ola Cabs',
 'Daalchini Technologies',
 'Ezyhaul',
 'Indus Os',
 'Healthassure',
 'House Of Msasaba',
 'Board Infinity',
 'Bira91',
 'Avail Finance',
 'Agara Labs',
 'Pratilipi',
 'Bolo App',
 'Okcredit',
 'Vogo Automotive Pvt. Ltd.',
 'Leegality',
 'Ola Electric',
 'Saahas Zero Waste',
 'Styledotme',
 'Glowroad',
 'Medlife',
 'Kabadiwala',
 'Tripoto',
 'Azah',
 'Setu',
 'Toppr',
 'Craftsvilla',
 'Unacademy',
 'My Healthcare',
 'Krazybee',
 'Increff',
 'Fleetx',
 'Nanoclean Global',
 'Samunnati Financial Intermediation & Services Pvt. Ltd',
 'Manch',
 'Guiddoo',
 'Career Anna',
 'Nagpur Wholesale',
 'Shopkirana',
 'Buildsupply',
 'Godesi',
 'Mobile Premier League',
 'A&R Bon Vivants',
 'Blackbuck',
 'Milkbasket',
 'Driveu',
 'Cleansecar',
 'Healthifyme',
 'Genius Corner',
 'Skillbox',
 'Signzy',
 'Roposo',
 'Northmist',
 'Origo Commodities India Pvt. Ltd',
 'Grover Zampa',
 'Droom',
 'Innov8',
 'Letstransport',
 'Daily Hunt',
 '3Hcare',
 'Happygoeasy',
 'Mad Street Den',
 'Pharmeasy',
 'Upwards',
 'Dishq',
 'Healthfin',
 'Samosa Labs',
 'Ziffyhomes',
 'My Omnamo',
 'Makemytrip',
 'Hansel Io',
 'Metro Bikes',
 'Quizizz',
 'Happy Emi',
 'Inthree',
 'Observe Ai',
 'Enakshi',
 'Eazydiner',
 'Finzy',
 'Rawpressery',
 'Pi Ventures',
 'Revv',
 'Zestmoney',
 'Shubh Loans',
 'Myupchar',
 'Narvar',
 'Leena Ai',
 'Biryani By Kilo',
 'Anchanto',
 'Zippserv',
 'Groww',
 'Avenue Growth',
 'Inicu',
 'Kinara Capital',
 'Shop 101',
 'Sambandh',
 '19Th Mile',
 '5Th Vital',
 'Mengage',
 'The Ken',
 'Housingman',
 'Paysense',
 'Yulu Bikes',
 'Vtion',
 'Log9 Materials',
 'Kidovators',
 'Black Soil',
 'Iqlect',
 'Entropik',
 'Bitla Software',
 'Thecapitalnet',
 'Healthsignz',
 'Cointribe',
 'Digiconectt',
 'Kashmir Box',
 'Crowdera',
 'Zoctr',
 'Meesho',
 'Theranosis',
 'Alpha Capital',
 'Eshakti',
 'Daily Ninja',
 'Nirogstreet',
 'Nivesh',
 "What'S Up Life",
 'Homelane',
 'Network Intelligence',
 'Elucidata',
 'Chrysalis',
 'Rentsher',
 'Drip Capital',
 'Wickedride',
 'Hipbar',
 'Sqqrl',
 'Paytm',
 'Sigtuple',
 'Wow Express',
 'Front Desk Ai',
 'Edureka',
 'Numeroseven',
 'Opentap',
 'Disprz',
 'Paisadukan',
 'I3Sysytems',
 'Earth Food',
 'Mfine',
 'Rocketium',
 'Vola',
 'Cashkumar',
 'Edyoo',
 'Aashiyaan',
 'Smartivity',
 'Bonphulapl',
 'Acko',
 'Hwell24',
 'Toffee',
 'Tonetag',
 'Events High',
 'Stellaps',
 'Credright',
 'Fitternity',
 'Synctag',
 'Benepik',
 'Indigolearn',
 'Vedantu',
 'Kaleidofin',
 'Pipabella',
 'Elemential',
 'Kriger Campus',
 'Loanzen',
 'Traveltriangle',
 'Letsmd',
 'Ayefinance',
 'Mintifi',
 'Icanstay',
 'Pregbuddy',
 'Lenskart',
 'Fyle Technologies',
 'Visit',
 'Doxper',
 'Nykaa',
 'Mihuru',
 'Trip Shelf',
 'Popxo',
 'Railyatri',
 '1Mg',
 'Rubique',
 'Samco',
 'Myloancare',
 'Buddy4Studdy',
 'Urban Ladder',
 'Kuvera',
 'Gramophone',
 'Wellthy',
 'Medgenome',
 'Finova Capital',
 'Hotelogix',
 'Livehealth',
 'Ad2Pro',
 'Coverfox',
 'Magicpin',
 'Healthcare',
 'Stumagz',
 'Availfinance',
 'Fingerlix',
 'Karma Healthcare',
 'Zappfresh',
 'Customersucessbox',
 'Gigindia',
 'Chargebee',
 'I2I Funding',
 'Slang Labs',
 'Urbanpiper',
 'Cash Suvidha',
 'Roadcast',
 'Smartcoin',
 'The Print',
 'Fynd',
 'Collegedekho',
 'Foodmemories',
 'Healthi',
 'Medtel',
 'Rupeek',
 'Webengage',
 'Wydr',
 'Cashify',
 'Holachef',
 'Awaaz De',
 'Imax Program',
 'Littlemore',
 'Shirsa Labs',
 'Moneyonmobile',
 'Petsutra',
 'Infibeam',
 'Happay',
 'Fincash',
 'Agricxlab',
 'The Healthy Billions',
 'Highradius',
 'Avishkaar Box',
 'Planys Technologies',
 'Lollypop',
 'Trilyo',
 'Credy',
 'Predible Health',
 'Clevertap',
 'Earlysalary',
 'Wotu',
 'Daaki',
 'Lendingkart',
 'Kinsane Entertainment Inc',
 'Tapzo',
 'Appario Retail Pvt Ltd.',
 'Kuants',
 'Streak',
 'Rubix',
 'Sharechat',
 'Paperflite',
 'Skillate',
 'Optacredit',
 'Aeon Learning',
 'Rao Iit Academy',
 'Glassic',
 'Greyatom',
 'Axio',
 'Ekincare',
 'The Wedding Brigade',
 'Peesafe',
 'Scapic',
 'Curefit',
 'Inurture',
 'Strata Enviro',
 'Dunzo',
 'Handytrain',
 'Mobycy',
 'Fintobox',
 'Mswipe',
 'The Label Life',
 'Cygnus Hospitals',
 'Inshorts',
 'Vahdam Tea',
 'Logic Roots',
 'Project Mudra',
 'Furlenco',
 'I Can Stay',
 'Fracktal Works',
 'Simility',
 'Shopholix',
 'Docsapp',
 'Capita World',
 'Tea Box',
 'Transversal Technologies',
 'Curofy',
 'Wedosky',
 'Purplle',
 'Sky Met Weather',
 'Springboard',
 'Peel Works',
 '9Stacks',
 'Your Quote',
 'Easyecom',
 'Igp.Com',
 'Specsmakers',
 'Garage On Road',
 'Foyr.Com',
 'Prest Loans',
 'Aadharapi.Com',
 'Freshboxx',
 'Vagupu',
 'Halaplay',
 'Kalpnik Technologies',
 'Hevo Data',
 'Smart Karma',
 'Leverage Edu',
 'Crayon Data',
 'Doctalk',
 'Coveiot',
 'Talentedge',
 'Fisdom',
 'Farmlink',
 'Openapp',
 'Nopaperforms',
 'Tilite Technologies Pvt. Ltd',
 'Mobiliz Ar',
 'Happily Unmarried',
 'Universal Sportsbiz Pvt. Ltd',
 'Hungry Foal',
 'Active Ai',
 'Sumeru',
 'Elderaid Wellness',
 'Omnia Information',
 'Josh Talks',
 'Reniso',
 'Kanhaiya',
 'Perspectico',
 'Onn Bikes',
 'Rapido',
 'Heckyl',
 'Nuvepro',
 'Redbook',
 'Credit Mate',
 'Mistay',
 'Wittyfeed',
 'Idg Ventures',
 'Tempgo',
 'Era',
 'Smaaash',
 'Chumbak',
 'Fr8',
 'Mobiefit',
 'Stanza Living',
 'Chqbook',
 'Homecapital',
 'Elanic',
 'Collpoll',
 'Little Black Book',
 'Oorjan',
 'Zefo',
 'Yaantra',
 'Farm Taaza',
 'Drivezy',
 'Slice Pay',
 'Agrowave',
 'Mygubbi',
 'Ibsfintech',
 'Letsservice',
 'Onestepup',
 'Thirdwatch',
 'Parallel Dots',
 'Easy Diner',
 'Stanplus',
 'Uclid',
 'Gapoon',
 'Chaayos',
 'Renew Buy',
 'Bank Bazaar',
 'Hasura',
 'Lenden Club',
 'Raw Pressery',
 'Cashe',
 'Park Easy',
 'Tagbox',
 'Fyre',
 'Ziploan',
 'Skillenza',
 'Chevon',
 'Propstory',
 'Spotdraft',
 'Big Basket',
 'Ofbusiness',
 'Olly Credit',
 'Cashfree',
 'Goldfarm',
 'Netmeds',
 'Aahaa Stores',
 'Canvera',
 'Primaryio',
 'Nest Education',
 'Lending Kart',
 'Gofro',
 'Oncostem',
 'Credit Vidya',
 'Tails Life',
 'Early Salary',
 'Seniority',
 'Farmizen',
 'Call Health',
 'Sattviko',
 'Tonbo Imaging',
 'Get My Parking',
 'Oyo Rooms',
 'Heterogenous',
 'Gurukul',
 'Wheelstreet',
 'Xprep',
 'The Moms Co',
 'Noticeboard',
 'Hwell24 Plus',
 'Savebc',
 'Gaming Monk',
 '91Springboard',
 'Homergize',
 'Yatra.Com',
 'Ace Turtle',
 'Vogo',
 'Synup',
 'Tinmen',
 'Cropin',
 'Sportobuddy',
 'Credifiable',
 'Inclov',
 'Multibhashi',
 'Transerve',
 'Fashalot',
 'Pitstop',
 'Gochoppers',
 'Aadyah',
 'Touchkin',
 'Ethinos',
 'Zepo',
 'Click2Clinic',
 'Speedbox',
 'Skill Connect',
 'Chai Point',
 'Lime Tray',
 'Coutloot',
 'Box My Space',
 'Curatio',
 'New Castle Technologies',
 'My Forex Eye',
 'Truxapp',
 'Crofarm',
 'Doodhwala',
 'Stayabode',
 'Moong Labs',
 'Sports Flashes',
 'Digilend',
 'Knab Finance',
 'Get Simpl',
 'Rootefy',
 'Uniphore',
 'Cerebroz',
 'Flochat',
 'Easygov',
 'Milk Basket',
 'Bombay Shaving Company',
 'Awign',
 'Indiez',
 'Ezetap',
 'Ink Monk',
 'Medinfi',
 'Mobikon',
 'Fieldassist',
 'Billion Loans',
 'Ecolibriumenergy',
 'Jumbotail',
 'Moglix',
 'Timesaverz',
 'Minjar',
 'Mycity4Kids',
 'Clip App',
 'Upwardly.In',
 'Autorox.Co',
 'Fabogo',
 'Flickstree',
 'Design Cafe',
 'Innoviti',
 'Vdeliver',
 'Bottr.Me',
 'Arcatron',
 'Qwikspec',
 'Vayana',
 'Mobiquest',
 'Ambee',
 'Ideal Insurance',
 'Hypernova Interactive',
 'Rentomojo',
 'Aircto',
 'Playablo',
 'Trupay',
 'Brick2Wall',
 'Fablestreet',
 'Monsoon Fintech',
 'Monkeybox',
 "Creator'S Gurukul",
 'Thinkerbell',
 'Jhakaas',
 'Bigstylist',
 'Gympik.Com',
 'Tripeur',
 'Rentongo',
 'Maxmywealth',
 'Spinny',
 'Healthbuds',
 'Ftcash',
 'Bhive Workspace',
 'Wayforward',
 'Gyandhan',
 'Growfitter',
 'Stratfit',
 'Multiplier Solutions',
 'Abi Health',
 'Stockal',
 'Guidoo',
 'Esahai.In',
 'Loanmeet',
 'Boxx.Ai',
 'Peesafe.In',
 'Vista Rooms',
 'Hypertrack',
 'Goodera',
 'Digit',
 'Vanitycask',
 'Mrneeds',
 'Moneytap',
 'Goodbox',
 'Portdesk',
 'Edgefx',
 'Healthintel',
 'Unbxd',
 'Darwinbox',
 'Forevershop',
 'Insider.In',
 'Grow Fit',
 'Fabulyst',
 'Oneassist',
 'Julia Computing',
 'Kissht',
 'Explore Life Traveling',
 'Loantap',
 'Voxweb',
 'Hug Innovations',
 'V Resorts',
 'Stashfin',
 'Formcept',
 'Spares Hub',
 'Fitraq',
 'Niki.Ai',
 'Fitpass',
 'Zinghr',
 'Tagos Design',
 'Power2Sme',
 'Innovapptive',
 '4Tigo',
 'Smecorner',
 'Zippserve',
 'Healthmir',
 'Uactive',
 'I-Lend',
 'Good Methods Global',
 'Balance App',
 'Yepme',
 'Nightstay',
 'Devourin',
 'Mygreens',
 'Curie Labs',
 'Uncanny Vision',
 'Sequretek',
 'Lucideus',
 'Vidooly',
 'Shopclues',
 'Fourth Ambit',
 'Chymera Vr',
 'Book My Diamond',
 'Ion Energy',
 'Legal Raasta',
 'Log 9 Materials',
 'Remit Guru',
 'Aequm',
 'Zapty',
 'Vernacular.Ai',
 'Telr',
 'Genie',
 'The Good Life',
 'Pumpkart',
 'Ezcred',
 'Healthsutra',
 'Zipgrid',
 'Travelspice',
 'Box8',
 'Gennext Students',
 'Whatsloan',
 'Cube Consumer Services',
 'Wowflux',
 'Collateral Medical',
 'Loadshare',
 'Simplilend',
 'Supr Daily',
 'Sastasundar',
 'Eruditus',
 'Testbook',
 'Tyre Express',
 'Waycool',
 'Perfios',
 'Whatfix',
 'Elastirun',
 'Trukky',
 'Konsult App',
 'Credit Sudhaar',
 'Dataweave',
 'Mech Mocha',
 'Startup Buddy',
 'Qorqi',
 'Twenty Two Motors',
 'Wonderchef',
 'Fastfox',
 'Omnify',
 'Capital Float',
 'Ninjacart',
 'Mergerware',
 'Clovia',
 'Emiza',
 'Hackerearth',
 'Squadrun',
 'Scoutmytrip',
 'Safetykart',
 'Weareholidays',
 'Myly',
 'Credihealth',
 'Navia Life Care',
 'Snackible',
 'Be U Salons',
 'Simulanis',
 'Innefu Security Consulting',
 'Whodat',
 'Absentia Vr',
 'Iotrek',
 'Wooplr',
 'Video Ken',
 'Faasos',
 'Niramai',
 'The Office Pass',
 'Urbanclap',
 'Myra',
 'Flytxt',
 'Howdy Ventures',
 'Stalkbuylove',
 'Zipgo',
 'Scootsy',
 'Autobix',
 'Eshiksha',
 'Sepalika',
 'Mintwalk',
 'Qriyo',
 'Belong',
 'Seenit',
 'Paalak',
 'Celes Care',
 'Karomi',
 'Red Carpet',
 'Kreate Konnect',
 'Creditmantri',
 'Lets Endorse',
 'Tydy',
 'Nactus',
 'Oho Shop',
 'Emojifi',
 'Juno Clinic',
 'Summerlabel',
 'Pickme',
 'Agrostar',
 'Zapr',
 'Data Resolve',
 'Book Servicing',
 'Blowhorn',
 'Rivigo',
 'Pipecandy',
 'Parentune',
 'Appbrowzer',
 'Magicbricks',
 'Peebuddy',
 'Iorderfresh',
 'Lavelle Networks',
 'Propertyshare',
 'Mydermacy',
 'Latestone',
 'Frapperz',
 'Mpaani',
 'Shilpmis',
 'Fitso',
 'Farmart',
 'Airpay',
 'Myglamm',
 'The Mons Co.',
 'Haqdarshak',
 'Ixigo',
 'Bizom',
 'Babyonboard',
 'Sport Flashes',
 'Wigzo',
 'Donething',
 'Zapyle',
 'Ithaka',
 'Perpule',
 "Byju'S",
 'Licious',
 'Emflux Motors',
 'Klinic App',
 'Oriano Solar',
 'Bigbasket',
 'Rooter',
 'Falconbrick',
 'Clodura',
 'Stockroom.Io',
 'Imanagemyhotel',
 'Inner Hour',
 'Travel Triangle',
 'Wandertrails',
 'Zenatix',
 'Mindyourfleet',
 'Edurev',
 'Voonik',
 '1Crowd',
 '48East',
 'Redesyn',
 'Flutura',
 'Wassup',
 'Better Mortgage',
 'Nurturey',
 'Fyle',
 'Gobumpr',
 'Connaizen',
 'Airzaar',
 'Truebil',
 'Yourstory',
 'Imaginate',
 'Aisle',
 'Townscript',
 'Leopetra',
 'Blood N Care',
 'True Balance',
 'Vebbler',
 'Lets Reap',
 'Oglas',
 'Staydobe',
 'Johari Shop',
 'Neostencil',
 'Taxsutra',
 'Tempogo',
 'Gofynd',
 'Vow Car Clinic',
 'Learntron',
 'Mobident',
 'Yostra',
 'Leap India',
 'Intelligence Node',
 'Securens',
 'Loan Frame',
 'Driveskool',
 'Instaoffice',
 'Hansel.Io',
 'Square Yards',
 'Roambee',
 'Paisawapas',
 'Iservice',
 'Secururax',
 'Leadburg',
 'Zolostays',
 'Oi Media',
 'Hipcouch',
 'Curiositi',
 'Tinystep',
 'Ketchupp',
 'Hoopy',
 'Ezytruk',
 'Kratikal',
 'Direct Create',
 'Vahdam Teas',
 'Pparke',
 'Weddingz.In',
 'Native Special',
 'Fitnapp',
 'Ethosh',
 'Messagif',
 'Smarthi',
 'Cron Systems',
 'Cuemath',
 'Chippersage',
 'Selectjobs',
 'Khel Now',
 'Nowfloats',
 'Lets Transport',
 'Betaout',
 'Wishberry',
 'Rml Agtech',
 'Loyaltyprime',
 'Instasafe',
 '99Games',
 'Airmed Labs',
 '99Perhour',
 'Kochi Post',
 'Intuit Things',
 'Cloudrino',
 'Fabx',
 'Maptags',
 'Yolo Health',
 'Heads Up For Tails',
 'Register My Marriage',
 'Sidqam',
 'India Lends',
 'Slide App',
 'Badiyajobs',
 'Streo',
 'Tygr',
 'Mr Hot Foods',
 'Urdoorstep',
 'Diro Labs',
 'Thb',
 'Lookatme',
 'Netree',
 'Bookeventz',
 'Tailslife',
 'Wealthapp',
 'Vehico',
 'Zest Money',
 'Gomechanic',
 'Stalk Buy Love',
 'Wittyparot',
 'Neuroequilibrium',
 'Xseed Education',
 'Rupaiya Exchange',
 'Doctor Insta',
 'Fresh Food Concepts',
 'Indifi',
 'Gocomet',
 'Fitmein',
 'Qacco',
 'Moengage',
 'Ten3T Health',
 'Trading Bells',
 "Serv'D",
 'Ideaforge',
 'Pocket Aces',
 'Tripshelf',
 'Nobroker',
 'Vivocarat',
 'Tiyo',
 'Zoomcar',
 'The Bluebook',
 'Vegetall',
 'Innoplexus',
 'Mindler',
 'Mcaffeine',
 'Enkast',
 'Myadvo',
 'Asocon',
 'Lexcomply',
 'The Postbox',
 'Pandorum Technologies',
 'Dekkho',
 'Shadowfox',
 'Shopx',
 'Justbooks',
 'Instantpay',
 'Pickmylaundry',
 'Laundryanna',
 'Zarget',
 'Doselect',
 'Easypolicy',
 'Browntape',
 'Connect India',
 'Corseco',
 'Vimmune',
 'The Gourmet Jar',
 'Medzin',
 'Bizongo',
 'Justride',
 'Iim Jobs',
 'Golflan',
 'Yottaasys',
 'Tone Tag',
 'Life In Control',
 'Active.Ai',
 'Elasticrun',
 'Playsimple',
 'Stasis Labs',
 'Scienaptic',
 'Koovs',
 'Lawrato',
 'Trip Tap Toe',
 'Pictor Imaging',
 'Gramcover',
 'Aermed',
 'Workindia',
 'Bats On Delivery',
 'Numberz.In',
 'Housing.Com',
 'Awesummly',
 'Volt',
 'Vymo',
 'Shubhloans',
 'Noddapp',
 'Infisecure',
 'Udaan',
 'Froyofit',
 'Betterplace',
 'Uclean',
 'Servify',
 'Hubilo',
 'Funongo',
 '121Policy',
 'Tapchief',
 'Kloseby',
 'Wholesalebox',
 'Crossahead',
 'Affordplan',
 'Shopsup',
 'Indofash',
 'Entropika',
 'Marianaiq',
 'Chai Thela',
 'Interviewpad',
 'Math Buddy',
 'Pulse',
 'Carcrew.In',
 'Merakisan',
 'Mystifly',
 'Helpchat',
 'World Art Community',
 'Giftxoxo',
 'Bharat Bazaar',
 'Goqii',
 'India Gifts Portal',
 'Netlinx',
 'Scandid',
 'Remitr',
 'Innerchef',
 'Appsdaily',
 'Muhurtmaza',
 'Azuro',
 'Neurosynaptic',
 'Ue Lifesciences',
 'Findmeashoe',
 'Realbox',
 'Sportido',
 'Gozefo',
 'Rayiot',
 'Kooh Sports',
 'Flexiloans',
 'Sibia Analytics',
 'Vithi.Com',
 'Deyor Camps',
 'Faballey',
 'Shoekonnect',
 'Maya',
 ...]

#### **Fixing the inconsistency in the 'Vertical' column -**

In [155]:
df['Vertical'].unique().tolist()

['Transportation',
 'E-commerce',
 'FinTech',
 'Fashion and Apparel',
 'Logistics',
 'Technology',
 'B2B-focused foodtech startup',
 'Finance',
 'Video',
 'Health and wellness',
 'Education',
 'Food and Beverage',
 'Health and Wellness',
 'Video Games',
 'Last Mile Transportation',
 'Healthcare',
 'Consumer Goods',
 'Advertising, Marketing',
 'SaaS',
 'IoT',
 'Information Technology',
 'Consumer Technology',
 'Accounting',
 'Retail',
 'E-Commerce',
 'EdTech',
 'Services',
 'Compliance',
 'Transport',
 'Tech',
 'Health Care',
 'Luxury Label',
 'Deep-Tech',
 'Digital Media',
 'Waste Management Service',
 'Social Media',
 'Fintech',
 'Edtech',
 'AI',
 'Nanotechnology',
 'Travel Tech',
 'Online Education',
 'Online Marketplace',
 'B2B',
 'SaaS, Ecommerce',
 'Gaming',
 'Food',
 'Food Tech',
 'Social Network',
 'Financial Tech',
 'Fashion',
 'Automobile',
 'Real Estate',
 'Logistics Tech',
 'Consumer Internet',
 'Fin-Tech',
 'Food-Tech',
 'Ed-Tech',
 'IT',
 'Ed-tech',
 'Clean-tech',
 'Fiinance',
 'Food & Beverages',
 'Media',
 'Publishing',
 'Food and Beverages',
 'Agriculture',
 'Entertainment',
 'Ecommerce',
 'Consumer internet',
 'ECommerce',
 'eCommerce',
 'Inspiration',
 'Storytelling',
 'Lifestyle',
 'Food & Beverage',
 'eCommece',
 'Consumer Portal',
 'Others',
 'ecommerce',
 'FMCG',
 'Reality',
 'Auto',
 'BFSI',
 'Consumer Interne',
 'Online Education Information platform',
 'Brand Licensing Startup',
 'Gourmet Food Discovery & Delivery platform',
 'Transportation & Logistics Platform',
 'Enterprise Marketing Automation platform',
 'Health, Wellness & Beauty Services App',
 'Digital Healthcare',
 'Last Minute Hotel Booking App',
 'Womens Fashion Wear Portal',
 'Product Learning platform',
 'Online Food ordering & Delivery platform',
 'Social Learning Platform',
 'Social Fitness platform',
 'On Demand Mobile app developer',
 'Car Maintenance & Management mobile app',
 'Splitting Bills Mobile App',
 'IOT Energy Management Analytics platform',
 'Custom Made furniture e-tailer',
 'eLearning platform',
 'Smart Safety Wearable Devices',
 'Cab Sharing service Mobile app',
 'Cloud Enterprise Mobility Platform',
 'Online Shopping Assistant Mobile app',
 'Home Cooked Food Order & Delivery platform',
 'Online School for Analytics learning',
 'Chat based personal Assistant App',
 'Picture creation & Social mobile app',
 'Nonbanking finance company',
 'eCommerce returns etailer',
 'Online Branded Furniture etailer',
 'Digital Analytics Platform',
 'Internet Network Infrastructure Services',
 'Supply Chain & Logistics Solutions',
 'Holiday Resort Chain',
 'Mobile Point of Sale solutions',
 'Test Automation SAAS platform',
 'Citizens Engagement Platform',
 'Indoor Navigation & Analytics Solutions',
 'Hyperlocal On-Demand Household Services platform',
 'Online RTI application services',
 'ECommerce Website Creation SAAS platform',
 'Wedding Venues & Vendors Marketplace',
 'Interface development platform for Government officials',
 'Modular Furnishings Marketplace',
 'Private Jet Bookings Marketplace',
 'Cab search Comparison & Booking platform',
 'Performance Optimization Platform for athletes',
 'Event Venue Booking Platform',
 'Digital Media Platform',
 'visual search and discovery platform',
 'End to End reverse logistics Solution platform',
 'Virtual Health consultation app',
 'Online Renting platform',
 'Data Science & UX design Learning platform',
 'Online marketplace for Chef Meals',
 'Electric Bike Manufacturers',
 'ECommerce platform solutions',
 'Online Media Publication',
 'International Hiring Platform',
 'Logistics Service Provider Marketplace',
 'Hyperlocal\\\\xc2\\\\xa0 Grocery Delivery Service',
 'Sports Education Platform',
 'Bike, Appliances Renting marketplace',
 'Online Marketplace for Industrial Goods',
 'Reward points mobile app',
 'Mobile accessories online store',
 'Content Discovery & reward points platform',
 'Artificial Intelligence platform',
 'Medical Consultation & Doctor appointment booking platform',
 'Mobile Fitness App',
 'Digital Coupons, Deal & Cashback aggregator app',
 'Mobile Game development & Design platform',
 'B2B eCommerce Marketplace',
 'Furniture and appliances rental platform',
 'B2B Merchandize platform',
 'Real Estate focused Tech platform',
 'Photographer Online search & booking platform',
 'Grocery Delivery platform',
 'Mobile Car Servicing appointment app',
 'New Curation Mobile App',
 'Mobile Wallet',
 'Online Food Ordering & Delivery platform',
 'Bus Aggregation and rental mobile app',
 'hyperlocal online Services platform',
 'WiFi \\xe2\\x80\\x93 first Cloud communication platform',
 'Alternate Mobile Monetization platform',
 'Online Food Ordering Marketplace',
 'Quick Service Restaurant & Online Delivery',
 'Online Loans Marketplace',
 'Budget Hotels Aggregator',
 'Efficient Energy Management platform',
 'Digital Intelligent learning platform',
 'Voice Call incentivization mobile app',
 'Online Counselling and psychological support platform',
 'Domestic Help Aggregation platform',
 'Home Stay & room rentals platform',
 'Selfie Mobile App',
 'Online Reputation Management Platform',
 'Online Grocery platform',
 'Online content platform for women',
 'Online Vehicle Spare Parts etailer',
 'Event Ticketing platform',
 'affordable Personal Healthcare Products',
 'Premium dining Lounges & restaurants',
 'Mobile Growth Hacking\\\\nPlatform',
 'Skill Training Startup',
 'Beauty and Wellness Marketplace',
 'Marketplace App for Bangkok',
 'On-demand Maids Service Provider',
 'eCommerce Product Search Engine',
 'Ready to cook packaged Foods',
 'Product Customization Platform',
 'Branded Food products online sales',
 'Talent platform for Fashion professionals',
 'Auto Insurance Online platform',
 'Hyperlocal Logistics Service Provider',
 'Cricket Management Mobile Game',
 'On Demand Laundry Service platform',
 'Ecommerce Discount & Cashback coupons platform',
 'Virtual Reality Headset creator',
 'Home Improvement Service platform',
 'mobile-only tasks marketplace',
 'Numerical Computing & Data Science Platform',
 'Designer fashion Jewellery Marketplace',
 'Online Products Discovery Platform',
 'Kids Tool kit for Innovation platform',
 'Mobile Learning Solutions',
 'conversational commerce mobile app',
 'Viral Content web Platform',
 'Express local delivery platform',
 'On-Demand Local Logistics provider',
 'Curated Freelancer Marketplace',
 'Online Taxi Rental Platform',
 'Smartwatch Maker',
 'Online Gourmet Food Marketplace',
 'Online Jewellery etailer',
 'Sales & Productivity Software',
 'ecommerce related software product platform',
 'Health-Tech platform',
 'Nightlife Discovery Mobile App',
 'Online Real Estate Marketplace',
 'Home Healthcare Services platform,',
 'Indian Ethnic Crafts Etailer',
 'Social platform for traders and investors',
 'Online Furniture, Home Appliances Rental Platform',
 'Healthcare Services Discovery platform',
 'Health and Beauty Services Marketplace',
 'Automotive Services platform',
 'Big Data Analytics Platform',
 'Mobile App based Loan disbursement platform',
 'On Demand Laundry Services App',
 'Content Management Software Solutions',
 'Fitness Tracking Management Solutions',
 'Hyperlocal healthcare product Delivery Service provider',
 'Online Lending Marketplace',
 'On Demand Beauty Services Platform',
 'Self Driven Rental Car Platform',
 'Education Content etailer',
 'Clud based Learning platform',
 'Talent Exchange & Talent Services Marketplace',
 'Two-Wheeler Taxi Service',
 'character merchandize sales platform',
 'Mobile Application Developer',
 'Ecommerce Delivery locker services',
 'extra curricular activities marketplace app',
 'Hyperlocal Online Home services provider',
 'Easy Business Loans platform',
 'Performance based Wholesale Marketplace',
 'Professional Services Marketplace',
 'Movie-on-demand platform',
 'us ticketing and fleet management platform',
 'Online Income Tax Filing platform',
 'Product discovery & recommendation platform',
 'Mobile Payments App',
 'Beauty & Wellness Products e-tailer',
 'Fashion jewelry and accessories e-tailer',
 'Online Consumer Lending platform',
 'Premium Apparel shopping portal',
 'Exclusive Platform for Doctors & Healthcare professionals',
 'Job Board',
 'Sports Management & Physical Education Business',
 'multi-sport program for preschoolers',
 'QSR & Online delivery portal',
 'Online Homeopathy Clinic',
 'E-Learning Service Provider',
 'Organic Food etailer',
 'Product Discovery & comparison App',
 'Online Apparels Fashion brand',
 'Home Cooked Food marketplace & Delivery',
 'Gesture based Mobile Development',
 'Hotel Mobile CRM Software platform',
 'Rental Accommodation Search platform',
 'Logistics Tech Platform',
 'Developer Portfolio Showcase platform',
 'Doctors Network Mobile App',
 'End-to-End Lending platform',
 'on-demand healthcare marketplace',
 '360-degree view creating platform',
 'Advertising & Marketing Community Networking platform',
 'Food Ordering & Delivery App',
 'Ride Sharing platform',
 'Online P2P lending marketplace',
 'B2B marketplace for industrial goods',
 'Cloud Based Collaboration platform',
 'global community for travellers',
 'Prepaid Bill manager App',
 'Mobile Only Shopping Assistant',
 'Mobile Messaging Assistant App',
 'Personalized Wish List creator app',
 'Music Streaming mobile app',
 'Raw Meat & Ready to eat food etailer',
 'Gym Discovery platform',
 'Online Purchase rewards app',
 'Home rental platform',
 'Crowdsourced Delivery platform',
 'Real Estate Insights platform',
 'Structural & Civil Engg Service Automation',
 'Startup Funding Marketplace',
 'Travel Destination Discovery platform',
 'Order Fulfillment SAAS platform',
 'Last Mile Delivery Service',
 'Healthcare IT Solutions & services',
 'Gourmet Meals Delivery',
 'Healthy Meals Food delivery platform',
 'Real Estate Mobile CRM',
 'Micro-Brewery',
 'Home Made Food Marketplace',
 'residential rental management platform',
 'Personalized Stock Intelligence Platform',
 'Personal Diagnostic Mobile App',
 'Online food ordering & Delivery service',
 'Hotel Aggregator & booking platform',
 'Online Logistics Platform',
 'Online Student & Campus Social Networking platform',
 'Professionals & Project Search Marketplace',
 'Online Payment Gateway',
 'Psychometric Test Online Software',
 'Location based Nightlife recommendation\\\\xc2\\\\xa0 Platform',
 'Professional Health Services Platform',
 'Hyperlocal Logistics Service',
 'Online user engagement platform',
 'Asset Financing platform',
 'Virtual Reality activity based learning platform',
 'Online Grocery Store',
 'Investment management platform',
 'Industrial Toons Marketplace',
 'Public Commute helper App',
 'Artificial Intelligence Ecommerce Chatbot',
 'Truck Aggregator & Logistics service',
 'Ridesharing Mobile app',
 'Food Discovery & Delivery Mobile app',
 'Competitive exam learning platform',
 'Document Digitization platform',
 'proximity marketing & Mobile Advertising platform',
 'Autorickshaw Aggregator & Booking platform',
 'FinTech Startup Incubation platform',
 'Payment Services platform',
 'Personalized Styling platform',
 'Luxury goods\\\\xc2\\\\xa0 Shopping Platform',
 'Food Delivery Platform',
 'Job Search Platform',
 'Doctor consultancy Mobile App',
 'Beauty & Wellness Services Marketplace',
 'Online Movie Review Platform',
 'ECommerce Brands\\\\xe2\\\\x80\\\\x99 Full Service Agency',
 'Cloud-based Hotel Booking Platform',
 'Community Driven News/Views Platform',
 'Study Material Marketplace',
 'Dairy Based Product Manufacturer',
 'Government Test Preparation platform',
 'Smart Report Cards for Schools',
 'Teacher empowerment platform',
 'Multilingual Test Preparation Platform',
 'Industrial Tools Marketplace',
 'Non Profit Organization to alleviate poverty',
 'Gym & Fitness Studios Subscription platform',
 'pre-used luxury item Marketplace',
 'pre-used apparel shopping mobile app',
 'Home Design & D\\\\xc3\\\\xa9cor platform',
 'Used Vehicles Marketplace',
 'Online Bus & Cab ticketing platform',
 'Mobile App testing platform',
 'Hyperlocal Delivery Services',
 'Early Cancer Detection Solutions',
 'Online Insurance Distribution Platform',
 'Mobile Marketing Automation Platform',
 'Prepaid Mobile Bill Manager App',
 'Chain of Tea Caf\\\\xc3\\\\xa9\\\\xe2\\\\x80\\\\x99s',
 'Branded Budget Hotel Marketplace',
 'Home Fitting & Fixtures Marketplace',
 'Food Subscription platform',
 'Wedding Planning Platform',
 'B2B Mobile Auction Marketplace',
 'ECommerce Data Analytics Platform',
 'Designer Merchandize Marketplace',
 'Online Food ordering & delivery',
 'Real Estate Broker Platform App',
 'Online Health & Wellness platform',
 'Internet of Things platform',
 'Diagnostic Labs aggregator platform',
 'Hyperlocal Delivery Platform',
 'Real-Time stock data platform',
 'Food discovery & table booking app',
 'coupons and cashback aggregator app',
 'Financial Products lead generation platform',
 'Sustainable Agri-inputs Firm',
 'Financial Services Portal',
 'Pre-owned games Marketplace',
 'Content-based Subscription eCommerce platform',
 'virtual reality, 3d simulation and stereoscopic products',
 'Online Interior Designing platform',
 'End-to-end Logistics platform',
 'Private Label Apparel sales',
 'Healthcare Consulting platform',
 'Stock Market Portal',
 'Cross-device retargeting platform',
 'Digital & Physical Publishing platform',
 'Data Driven Publishing platform',
 'Employee OnBoarding & Orientation platform',
 'Solar Power Solutions company',
 'Online Meat Ordering platform',
 'online meal-booking platform for train travelers',
 'hyperlocal delivery platform',
 'Ecommerce Product recommendation platform',
 'Activity Based Social Network',
 'Fashion Discovery platform',
 'Consumer lending marketplace',
 'Big Data Management Platform',
 'Budget Accommodation Platform',
 'Local Mobile OS',
 'Digital Signal processing platform',
 'Restaurant Discount app',
 'Tech-enabled learning',
 'ECommerce Logistics provider',
 'on-demand home beauty and wellness portal',
 'Self Driven Car rental',
 'Energy & Environment Online Marketplace',
 'User Engagment & Analytics platform',
 'On-Demand Delivery Logistics',
 'fund raising platform for startups',
 'Hyperlocal Handyman services',
 'hotel booking app',
 'Rental Accomodation finder',
 'Tech Platform for property brokers',
 'Luxury Apparel rental',
 'App security\\\\xc2\\\\xa0 testing platform',
 'anonymous bulletin board app',
 'Travel community platform',
 'Crowd funding platform',
 'Car & Bike ecommerce platform',
 'Fast food Chain Franchisee',
 'Loyalty Programs & Reward Points',
 'Energy saving solutions provider',
 'Self-Storage Spaces',
 'Grocery retail Mobile app',
 'Taxi Rental platform',
 'Machine Learning Platform',
 'mobile social network',
 'Hyper-Local Ecommerce',
 'Online printing marketplace',
 'mobile payment software platform',
 'Home Design & D\\\\xc3\\\\xa9cor solutions',
 'Quick Service Restaurant Chain',
 'Subscription based Online Grocery platform',
 'Credit Card Fraud protection solutions',
 'Career Community for Women',
 'Mutual Fund Investing platform',
 'Ecommerce Marketing Software Platform',
 'Digital Marketing automation solution',
 'Mobile Commerce for Farmers',
 'Picture based Social App',
 'Logistics service platform',
 'On-Demand Beauty Services',
 'Exam Preparation Platform',
 'Startup Focused Online Publisher',
 'Waste Management Solutions',
 'App based Fitness coaching',
 'On demand cleaning & fixing services',
 'Beauty & Lifestyle platform',
 'on-demand delivery service',
 'Data Analytics Platform',
 'Deep Learning Cloud Algorithms',
 'Location based engagement & rewards platform',
 'Online Identity Verification Services platform',
 'Corporate Wellness App',
 'Fashion Search & Review Platform',
 'Hyperlocal Maintenance, Repair & Cleaning services',
 'pre-owned Luxury online apparel seller',
 'Online Diagnostic Tests Marketplace',
 'Online marketplace for Photographers',
 'Visual Blogging platform',
 'Food Customer analytics platform',
 'Professional Service Appointment booking service',
 'Scientific Horoscope Online Assistance platform',
 'Tech enabled AC bus service',
 'On-Demand App based Professional service provider',
 'Restaurant Reservation Platform',
 'Cross-channel CRM platform',
 'Professional Custom creators Marketplace',
 'on-Demand Washing & Dry-Cleaning',
 'On-Demand Beauty Service',
 'solar products and services marketplace',
 'Online Food Community Platform',
 'Private Cloud Networks SAAS platform',
 'Education Marketplace',
 'Cloud Based Hotel Sales Platform',
 'online recipe sharing platform',
 'Beauty & Lifestyle Mobile Marketplace',
 'QSR Restaurant Chain',
 'Digital Media publishing platform',
 'Online Coffee Delivery platform',
 'Language Localization Cloud platform',
 'Big Data & predictive Analysis Platform',
 'Business IT Intelligence Services',
 'CRM / Analytics platform',
 'Ed-Tech Platform',
 'Cab rental Mobile app',
 'IT infrastructure & Data Center services',
 'Used Car Marketplace',
 'Language Learning App',
 'Mobile Fitness Marketplace',
 'Custom Merchandize platform',
 'P2P Pre-owned goods marketplace',
 'Custom Furniture Marketplace',
 'Online Tailoring Services',
 'Rail Ticket Confirmation predictor',
 'Hyperlocal Goods marketplace',
 'Budget Accommodation aggregator',
 'Real Estate Rating & Analysis',
 'Food Delivery platform',
 'Food Discovery App',
 'Big Data & Analytics platform',
 'Coupon Aggregator Platform',
 'Electric Scooter manufacturer',
 'Online Food-Tech Platform',
 'Celebrity Fashion Brand',
 'Online Finance lending platform',
 'Healthcare Mobile App',
 'Self-driven vehicle rental',
 '\\\\xc2\\\\xa0News Aggregator mobile app',
 '\\\\xc2\\\\xa0Online Jewellery Store',
 '\\\\xc2\\\\xa0Fashion Info Aggregator App',
 '\\\\xc2\\\\xa0Online Study Notes Marketplace',
 '\\\\xc2\\\\xa0Pre-School Chain',
 '\\\\xc2\\\\xa0Premium Loyalty Rewards Point Management',
 '\\\\xc2\\\\xa0Contact Center Software Platform',
 '\\\\xc2\\\\xa0Casual Dining restaurant Chain',
 '\\\\xc2\\\\xa0Online Grocery Delivery',
 'Online comparison engine',
 'Residential Rental management platform',
 'Physical Storage warehouses',
 'Tech Recruitment platform',
 'Bike Rental Platform',
 'Tech enabled logistics platform',
 'Restaurant customer engagement platform',
 'Live video streaming app',
 'Hyper local logistics platform',
 'Crowd Funding Platform',
 'F&B sector Mobile Payment platform',
 'Industrial Supplies B2B ecommerce',
 'Online budget hotel chain',
 'Payment Solutions platform',
 'Online Hiring Platform',
 'Organic Food ecommerce',
 'Luxury Rental Homes',
 'Online Grocers',
 'Casual Dating App',
 'Travel information portal',
 'Fitness Marketplace',
 'Private Jet/ Helicopter Marketplace',
 'Real Estate Broker network App',
 'Ethnic/ Traditional Fashion Store',
 'Used Bikes Marketplace',
 'Spa & Salon Management Software',
 'B2B logistics delivery platform',
 'Logistics Automation Platform',
 'Hyperlocal food & grocery store',
 'Hyperlocal Handyman Services',
 'Medical Tech Instruments',
 'Innovative Water Solutions',
 'Online Jewelry Store',
 'Business intelligence & Analytics',
 'Used Vehicle Marketplace',
 'Educational Board Games',
 'Chinese food delivery',
 'On-Demand Laundry & Dry cleaning App',
 'On-Demand Car services App',
 'Hyperlocal Grocery App',
 'Online Curated Holiday package bookings',
 'Hasbro Toy Manufacturer',
 'Beauty and Wellness Platform',
 'Healthy Food Manufacturer',
 'Online Learning Platform',
 'Healthy Food Online Community',
 'Used two-wheeler Marketplace',
 'Online Fashion Video Portal',
 'Probiotic Technology Products Manufacturer',
 'Architectural Design & Consulting',
 'Preventive Healthcare Services',
 'Tech-enabled Rural Healthcare Services',
 'Engineering Innovations',
 'Real Estate Intelligence Platform',
 'Online Car Rental Affiliates',
 'Data Center Software platform',
 'Online City & Lifestyle Guide',
 'P2P Payments platform',
 'Bespoke Merchandize Marketplace',
 'Women Lifestyle Marketplace',

In [156]:
#By manual assessment we get the inconsistency in vertical names ----> Resolving that 
#Fix the 'é' (like in Café or Décor)
df['Vertical'] = df['Vertical'].str.replace(r'\\\\xc3\\\\xa9', 'e', regex=True)

# 2. Fix the apostrophe (like in Byju's or Caf's)
df['Vertical'] = df['Vertical'].str.replace(r'\\\\xe2\\\\x80\\\\x99', "'", regex=True)

# 3. Wipe out the broken space junk (\\\\xc2\\\\xa0)
df['Vertical'] = df['Vertical'].str.replace(r'\\\\xc2\\\\xa0', ' ', regex=True)

# 4. Fix Newlines (\\\\Nplatform) found in 'Mobile Growth Hacking'
df['Vertical'] = df['Vertical'].str.replace(r'\\\\n', ' ', regex=True, case=False)

# 5. Final Polish: Fix casing and remove extra whitespace
df['Vertical'] = df['Vertical'].str.strip().str.title()

# 6. Optional: Clean up repetitive suffixes to help grouping
# This merges "Booking Platform" and "Booking App" into just "Booking"
df['Vertical'] = df['Vertical'].str.replace(r'\s+(Platform|App|Marketplace|Service|Solution)s?\b', '', regex=True, case=False)

In [157]:
df['Vertical'].unique().tolist()

['Transportation',
 'E-Commerce',
 'Fintech',
 'Fashion And Apparel',
 'Logistics',
 'Technology',
 'B2B-Focused Foodtech Startup',
 'Finance',
 'Video',
 'Health And Wellness',
 'Education',
 'Food And Beverage',
 'Video Games',
 'Last Mile Transportation',
 'Healthcare',
 'Consumer Goods',
 'Advertising, Marketing',
 'Saas',
 'Iot',
 'Information Technology',
 'Consumer Technology',
 'Accounting',
 'Retail',
 'Edtech',
 'Services',
 'Compliance',
 'Transport',
 'Tech',
 'Health Care',
 'Luxury Label',
 'Deep-Tech',
 'Digital Media',
 'Waste Management',
 'Social Media',
 'Ai',
 'Nanotechnology',
 'Travel Tech',
 'Online Education',
 'Online',
 'B2B',
 'Saas, Ecommerce',
 'Gaming',
 'Food',
 'Food Tech',
 'Social Network',
 'Financial Tech',
 'Fashion',
 'Automobile',
 'Real Estate',
 'Logistics Tech',
 'Consumer Internet',
 'Fin-Tech',
 'Food-Tech',
 'Ed-Tech',
 'It',
 'Clean-Tech',
 'Fiinance',
 'Food & Beverages',
 'Media',
 'Publishing',
 'Food And Beverages',
 'Agriculture',
 'Entertainment',
 'Ecommerce',
 'Inspiration',
 'Storytelling',
 'Lifestyle',
 'Food & Beverage',
 'Ecommece',
 'Consumer Portal',
 'Others',
 'Fmcg',
 'Reality',
 'Auto',
 'Bfsi',
 'Consumer Interne',
 'Online Education Information',
 'Brand Licensing Startup',
 'Gourmet Food Discovery & Delivery',
 'Transportation & Logistics',
 'Enterprise Marketing Automation',
 'Health, Wellness & Beauty',
 'Digital Healthcare',
 'Last Minute Hotel Booking',
 'Womens Fashion Wear Portal',
 'Product Learning',
 'Online Food Ordering & Delivery',
 'Social Learning',
 'Social Fitness',
 'On Demand Mobile Developer',
 'Car Maintenance & Management Mobile',
 'Splitting Bills Mobile',
 'Iot Energy Management Analytics',
 'Custom Made Furniture E-Tailer',
 'Elearning',
 'Smart Safety Wearable Devices',
 'Cab Sharing Mobile',
 'Cloud Enterprise Mobility',
 'Online Shopping Assistant Mobile',
 'Home Cooked Food Order & Delivery',
 'Online School For Analytics Learning',
 'Chat Based Personal Assistant',
 'Picture Creation & Social Mobile',
 'Nonbanking Finance Company',
 'Ecommerce Returns Etailer',
 'Online Branded Furniture Etailer',
 'Digital Analytics',
 'Internet Network Infrastructure',
 'Supply Chain & Logistics',
 'Holiday Resort Chain',
 'Mobile Point Of Sale',
 'Test Automation Saas',
 'Citizens Engagement',
 'Indoor Navigation & Analytics',
 'Hyperlocal On-Demand Household',
 'Online Rti Application',
 'Ecommerce Website Creation Saas',
 'Wedding Venues & Vendors',
 'Interface Development For Government Officials',
 'Modular Furnishings',
 'Private Jet Bookings',
 'Cab Search Comparison & Booking',
 'Performance Optimization For Athletes',
 'Event Venue Booking',
 'Visual Search And Discovery',
 'End To End Reverse Logistics',
 'Virtual Health Consultation',
 'Online Renting',
 'Data Science & Ux Design Learning',
 'Online For Chef Meals',
 'Electric Bike Manufacturers',
 'Online Media Publication',
 'International Hiring',
 'Logistics Provider',
 'Hyperlocal  Grocery Delivery',
 'Sports Education',
 'Bike, Appliances Renting',
 'Online For Industrial Goods',
 'Reward Points Mobile',
 'Mobile Accessories Online Store',
 'Content Discovery & Reward Points',
 'Artificial Intelligence',
 'Medical Consultation & Doctor Appointment Booking',
 'Mobile Fitness',
 'Digital Coupons, Deal & Cashback Aggregator',
 'Mobile Game Development & Design',
 'B2B Ecommerce',
 'Furniture And Appliances Rental',
 'B2B Merchandize',
 'Real Estate Focused Tech',
 'Photographer Online Search & Booking',
 'Grocery Delivery',
 'Mobile Car Servicing Appointment',
 'New Curation Mobile',
 'Mobile Wallet',
 'Bus Aggregation And Rental Mobile',
 'Hyperlocal Online',
 'Wifi \\Xe2\\X80\\X93 First Cloud Communication',
 'Alternate Mobile Monetization',
 'Online Food Ordering',
 'Quick Restaurant & Online Delivery',
 'Online Loans',
 'Budget Hotels Aggregator',
 'Efficient Energy Management',
 'Digital Intelligent Learning',
 'Voice Call Incentivization Mobile',
 'Online Counselling And Psychological Support',
 'Domestic Help Aggregation',
 'Home Stay & Room Rentals',
 'Selfie Mobile',
 'Online Reputation Management',
 'Online Grocery',
 'Online Content For Women',
 'Online Vehicle Spare Parts Etailer',
 'Event Ticketing',
 'Affordable Personal Healthcare Products',
 'Premium Dining Lounges & Restaurants',
 'Mobile Growth Hacking',
 'Skill Training Startup',
 'Beauty And Wellness',
 'Marketplace For Bangkok',
 'On-Demand Maids Provider',
 'Ecommerce Product Search Engine',
 'Ready To Cook Packaged Foods',
 'Product Customization',
 'Branded Food Products Online Sales',
 'Talent For Fashion Professionals',
 'Auto Insurance Online',
 'Hyperlocal Logistics Provider',
 'Cricket Management Mobile Game',
 'On Demand Laundry',
 'Ecommerce Discount & Cashback Coupons',
 'Virtual Reality Headset Creator',
 'Home Improvement',
 'Mobile-Only Tasks',
 'Numerical Computing & Data Science',
 'Designer Fashion Jewellery',
 'Online Products Discovery',
 'Kids Tool Kit For Innovation',
 'Mobile Learning',
 'Conversational Commerce Mobile',
 'Viral Content Web',
 'Express Local Delivery',
 'On-Demand Local Logistics Provider',
 'Curated Freelancer',
 'Online Taxi Rental',
 'Smartwatch Maker',
 'Online Gourmet Food',
 'Online Jewellery Etailer',
 'Sales & Productivity Software',
 'Ecommerce Related Software Product',
 'Health-Tech',
 'Nightlife Discovery Mobile',
 'Online Real Estate',
 'Home Healthcare,',
 'Indian Ethnic Crafts Etailer',
 'Social For Traders And Investors',
 'Online Furniture, Home Appliances Rental',
 'Healthcare Discovery',
 'Health And Beauty',
 'Automotive',
 'Big Data Analytics',
 'Mobile Based Loan Disbursement',
 'Content Management Software',
 'Fitness Tracking Management',
 'Hyperlocal Healthcare Product Delivery Provider',
 'Online Lending',
 'On Demand Beauty',
 'Self Driven Rental Car',
 'Education Content Etailer',
 'Clud Based Learning',
 'Talent Exchange & Talent',
 'Two-Wheeler Taxi',
 'Character Merchandize Sales',
 'Mobile Application Developer',
 'Ecommerce Delivery Locker',
 'Extra Curricular Activities',
 'Hyperlocal Online Home Provider',
 'Easy Business Loans',
 'Performance Based Wholesale',
 'Professional',
 'Movie-On-Demand',
 'Us Ticketing And Fleet Management',
 'Online Income Tax Filing',
 'Product Discovery & Recommendation',
 'Mobile Payments',
 'Beauty & Wellness Products E-Tailer',
 'Fashion Jewelry And Accessories E-Tailer',
 'Online Consumer Lending',
 'Premium Apparel Shopping Portal',
 'Exclusive For Doctors & Healthcare Professionals',
 'Job Board',
 'Sports Management & Physical Education Business',
 'Multi-Sport Program For Preschoolers',
 'Qsr & Online Delivery Portal',
 'Online Homeopathy Clinic',
 'E-Learning Provider',
 'Organic Food Etailer',
 'Product Discovery & Comparison',
 'Online Apparels Fashion Brand',
 'Home Cooked Food & Delivery',
 'Gesture Based Mobile Development',
 'Hotel Mobile Crm Software',
 'Rental Accommodation Search',
 'Developer Portfolio Showcase',
 'Doctors Network Mobile',
 'End-To-End Lending',
 'On-Demand Healthcare',
 '360-Degree View Creating',
 'Advertising & Marketing Community Networking',
 'Food Ordering & Delivery',
 'Ride Sharing',
 'Online P2P Lending',
 'B2B For Industrial Goods',
 'Cloud Based Collaboration',
 'Global Community For Travellers',
 'Prepaid Bill Manager',
 'Mobile Only Shopping Assistant',
 'Mobile Messaging Assistant',
 'Personalized Wish List Creator',
 'Music Streaming Mobile',
 'Raw Meat & Ready To Eat Food Etailer',
 'Gym Discovery',
 'Online Purchase Rewards',
 'Home Rental',
 'Crowdsourced Delivery',
 'Real Estate Insights',
 'Structural & Civil Engg Automation',
 'Startup Funding',
 'Travel Destination Discovery',
 'Order Fulfillment Saas',
 'Last Mile Delivery',
 'Healthcare It &',
 'Gourmet Meals Delivery',
 'Healthy Meals Food Delivery',
 'Real Estate Mobile Crm',
 'Micro-Brewery',
 'Home Made Food',
 'Residential Rental Management',
 'Personalized Stock Intelligence',
 'Personal Diagnostic Mobile',
 'Hotel Aggregator & Booking',
 'Online Logistics',
 'Online Student & Campus Social Networking',
 'Professionals & Project Search',
 'Online Payment Gateway',
 'Psychometric Test Online Software',
 'Location Based Nightlife Recommendation',
 'Professional Health',
 'Hyperlocal Logistics',
 'Online User Engagement',
 'Asset Financing',
 'Virtual Reality Activity Based Learning',
 'Online Grocery Store',
 'Investment Management',
 'Industrial Toons',
 'Public Commute Helper',
 'Artificial Intelligence Ecommerce Chatbot',
 'Truck Aggregator & Logistics',
 'Ridesharing Mobile',
 'Food Discovery & Delivery Mobile',
 'Competitive Exam Learning',
 'Document Digitization',
 'Proximity Marketing & Mobile Advertising',
 'Autorickshaw Aggregator & Booking',
 'Fintech Startup Incubation',
 'Payment',
 'Personalized Styling',
 'Luxury Goods  Shopping',
 'Food Delivery',
 'Job Search',
 'Doctor Consultancy Mobile',
 'Beauty & Wellness',
 'Online Movie Review',
 "Ecommerce Brands' Full Agency",
 'Cloud-Based Hotel Booking',
 'Community Driven News/Views',
 'Study Material',
 'Dairy Based Product Manufacturer',
 'Government Test Preparation',
 'Smart Report Cards For Schools',
 'Teacher Empowerment',
 'Multilingual Test Preparation',
 'Industrial Tools',
 'Non Profit Organization To Alleviate Poverty',
 'Gym & Fitness Studios Subscription',
 'Pre-Used Luxury Item',
 'Pre-Used Apparel Shopping Mobile',
 'Home Design & Decor',
 'Used Vehicles',
 'Online Bus & Cab Ticketing',
 'Mobile Testing',
 'Hyperlocal Delivery',
 'Early Cancer Detection',
 'Online Insurance Distribution',
 'Mobile Marketing Automation',
 'Prepaid Mobile Bill Manager',
 "Chain Of Tea Cafe'S",
 'Branded Budget Hotel',
 'Home Fitting & Fixtures',
 'Food Subscription',
 'Wedding Planning',
 'B2B Mobile Auction',
 'Ecommerce Data Analytics',
 'Designer Merchandize',
 'Real Estate Broker',
 'Online Health & Wellness',
 'Internet Of Things',
 'Diagnostic Labs Aggregator',
 'Real-Time Stock Data',
 'Food Discovery & Table Booking',
 'Coupons And Cashback Aggregator',
 'Financial Products Lead Generation',
 'Sustainable Agri-Inputs Firm',
 'Financial Portal',
 'Pre-Owned Games',
 'Content-Based Subscription Ecommerce',
 'Virtual Reality, 3D Simulation And Stereoscopic Products',
 'Online Interior Designing',
 'End-To-End Logistics',
 'Private Label Apparel Sales',
 'Healthcare Consulting',
 'Stock Market Portal',
 'Cross-Device Retargeting',
 'Digital & Physical Publishing',
 'Data Driven Publishing',
 'Employee Onboarding & Orientation',
 'Solar Power Company',
 'Online Meat Ordering',
 'Online Meal-Booking For Train Travelers',
 'Ecommerce Product Recommendation',
 'Activity Based Social Network',
 'Fashion Discovery',
 'Consumer Lending',
 'Big Data Management',
 'Budget Accommodation',
 'Local Mobile Os',
 'Digital Signal Processing',
 'Restaurant Discount',
 'Tech-Enabled Learning',
 'Ecommerce Logistics Provider',
 'On-Demand Home Beauty And Wellness Portal',
 'Self Driven Car Rental',
 'Energy & Environment Online',
 'User Engagment & Analytics',
 'On-Demand Delivery Logistics',
 'Fund Raising For Startups',
 'Hyperlocal Handyman',
 'Hotel Booking',
 'Rental Accomodation Finder',
 'Tech For Property Brokers',
 'Luxury Apparel Rental',
 'App Security  Testing',
 'Anonymous Bulletin Board',
 'Travel Community',
 'Crowd Funding',
 'Car & Bike Ecommerce',
 'Fast Food Chain Franchisee',
 'Loyalty Programs & Reward Points',
 'Energy Saving Provider',
 'Self-Storage Spaces',
 'Grocery Retail Mobile',
 'Taxi Rental',
 'Machine Learning',
 'Mobile Social Network',
 'Hyper-Local Ecommerce',
 'Online Printing',
 'Mobile Payment Software',
 'Quick Restaurant Chain',
 'Subscription Based Online Grocery',
 'Credit Card Fraud Protection',
 'Career Community For Women',
 'Mutual Fund Investing',
 'Ecommerce Marketing Software',
 'Digital Marketing Automation',
 'Mobile Commerce For Farmers',
 'Picture Based Social',
 'On-Demand Beauty',
 'Exam Preparation',
 'Startup Focused Online Publisher',
 'App Based Fitness Coaching',
 'On Demand Cleaning & Fixing',
 'Beauty & Lifestyle',
 'On-Demand Delivery',
 'Data Analytics',
 'Deep Learning Cloud Algorithms',
 'Location Based Engagement & Rewards',
 'Online Identity Verification',
 'Corporate Wellness',
 'Fashion Search & Review',
 'Hyperlocal Maintenance, Repair & Cleaning',
 'Pre-Owned Luxury Online Apparel Seller',
 'Online Diagnostic Tests',
 'Online For Photographers',
 'Visual Blogging',
 'Food Customer Analytics',
 'Professional Appointment Booking',
 'Scientific Horoscope Online Assistance',
 'Tech Enabled Ac Bus',
 'On-Demand Based Professional Provider',
 'Restaurant Reservation',
 'Cross-Channel Crm',
 'Professional Custom Creators',
 'On-Demand Washing & Dry-Cleaning',
 'Solar Products And',
 'Online Food Community',
 'Private Cloud Networks Saas',
 'Cloud Based Hotel Sales',
 'Online Recipe Sharing',
 'Beauty & Lifestyle Mobile',
 'Qsr Restaurant Chain',
 'Digital Media Publishing',
 'Online Coffee Delivery',
 'Language Localization Cloud',
 'Big Data & Predictive Analysis',
 'Business It Intelligence',
 'Crm / Analytics',
 'Cab Rental Mobile',
 'It Infrastructure & Data Center',
 'Used Car',
 'Language Learning',
 'Custom Merchandize',
 'P2P Pre-Owned Goods',
 'Custom Furniture',
 'Online Tailoring',
 'Rail Ticket Confirmation Predictor',
 'Hyperlocal Goods',
 'Budget Accommodation Aggregator',
 'Real Estate Rating & Analysis',
 'Food Discovery',
 'Big Data & Analytics',
 'Coupon Aggregator',
 'Electric Scooter Manufacturer',
 'Online Food-Tech',
 'Celebrity Fashion Brand',
 'Online Finance Lending',
 'Healthcare Mobile',
 'Self-Driven Vehicle Rental',
 'News Aggregator Mobile',
 'Online Jewellery Store',
 'Fashion Info Aggregator',
 'Online Study Notes',
 'Pre-School Chain',
 'Premium Loyalty Rewards Point Management',
 'Contact Center Software',
 'Casual Dining Restaurant Chain',
 'Online Grocery Delivery',
 'Online Comparison Engine',
 'Physical Storage Warehouses',
 'Tech Recruitment',
 'Bike Rental',
 'Tech Enabled Logistics',
 'Restaurant Customer Engagement',
 'Live Video Streaming',
 'Hyper Local Logistics',
 'F&B Sector Mobile Payment',
 'Industrial Supplies B2B Ecommerce',
 'Online Budget Hotel Chain',
 'Online Hiring',
 'Organic Food Ecommerce',
 'Luxury Rental Homes',
 'Online Grocers',
 'Casual Dating',
 'Travel Information Portal',
 'Fitness',
 'Private Jet/ Helicopter',
 'Real Estate Broker Network',
 'Ethnic/ Traditional Fashion Store',
 'Used Bikes',
 'Spa & Salon Management Software',
 'B2B Logistics Delivery',
 'Logistics Automation',
 'Hyperlocal Food & Grocery Store',
 'Medical Tech Instruments',
 'Innovative Water',
 'Online Jewelry Store',
 'Business Intelligence & Analytics',
 'Used Vehicle',
 'Educational Board Games',
 'Chinese Food Delivery',
 'On-Demand Laundry & Dry Cleaning',
 'On-Demand Car',
 'Hyperlocal Grocery',
 'Online Curated Holiday Package Bookings',
 'Hasbro Toy Manufacturer',
 'Healthy Food Manufacturer',
 'Online Learning',
 'Healthy Food Online Community',
 'Used Two-Wheeler',
 'Online Fashion Video Portal',
 'Probiotic Technology Products Manufacturer',
 'Architectural Design & Consulting',
 'Preventive Healthcare',
 'Tech-Enabled Rural Healthcare',
 'Engineering Innovations',
 'Real Estate Intelligence',
 'Online Car Rental Affiliates',
 'Data Center Software',
 'Online City & Lifestyle Guide',
 'P2P Payments',
 'Bespoke Merchandize',
 'Women Lifestyle',
 'Video Intelligence',
 'Renewable Energy',
 'Healthcare Provider',
 'Auto Rickshaw Based',
 'Artist / Designer',
 'Private Label Lingerie Ecommerce',
 'Mobile Commerce',
 'Digital Marketing',
 'Travel Guide Mobile',
 'Fashion Ecommerce Store',
 'Mobile Compression Software',
 'Peer To Peer Lending',
 'Global Healthcare Products',
 'Skill Training & Placement',
 'Intra-City Logistics',
 'Online Tiffin Aggregator',
 'Electronic Goods Recycling',
 'Online Coupon & Comparison',
 'Parents & Kids Online',
 'Dental Clinic Chain',
 'On-Demand Logistics',
 '3D Printer Manufacturer',
 'It / Customer Engagement Consulting',
 'Health & Fitness',
 'Home',
 'Financial',
 'Social Network For Artists',
 'Data Driven Recruitment Recommendation',
 'Travel Search Engine',
 'Brain Games',
 'Video Advertisement',
 'Algorithmic Match Making',
 'Mobile Chat Based Concierge',
 'Online Budget Hotel Booking',
 'Science Learning',
 'App Analytics',
 'Micro Finance',
 'Freight Logistics',
 'Credit Management',
 'Hyperlocal',
 'Beauty Mobile',
 'Marketing / Advertising Automation',
 'Online Lingerie',
 'Railways Information Mobile',
 'Hyperlocal Grocery Delivery',
 'Flat Rental Mobile',
 'Wealth Management',
 'Fund Raising',
 'Workforce Management Software',
 'Online Art',
 'Online Food Delivery',
 'Affordable Education',
 'Career Development',
 'Real Estate Advisory',
 'Banking Analytics',
 'Customer Engagement',
 'Speech Recognition',
 'Online Product Comparison',
 'Online Security',
 'Online Medical Diagnostic',
 'Cloud Data Integration',
 'Mobile Laundry Cleaning',
 'Service-On-Demand Mobile',
 'Intelligent Data Analytics',
 'Online Office Rental',
 'Lifestyle Ecommerce Portal',
 'Online Fashion Aggregator',
 'Online Job Skills Showcase',
 'Online News Media',
 'Enterprise Communication',
 'Offline Tea Chain',
 'Business Messaging',
 'Health Mobile',
 'Online Ed-Tech',
 'Hyperlocal Mobile',
 'Trucking Logistic Operations',
 'B2C Messaging',
 'Rooftop Solar Plants',
 'Online Car Portal',
 'Online Table Reservation',
 'Parents Focused Web Content',
 'Payments Provider',
 'On-Demand',
 'On-Demand Business Messaging',
 'Online Home Decor',
 'Api Workflow',
 'Affordable Hotel Booking Online',
 'Logistics Intelligence',
 'Last Mile Logistics',
 'Self-Driven Car Rental',
 'Weight Management',
 'Web Content Publishing',
 'Location Based',
 'Video Streaming',
 'Price Comparison',
 'Travel Entertainment',
 'Device Repair Svcs',
 'Premium Beverages',
 'Digital / Mobile Wallet',
 'Interactive  How-To Guides',
 'Mobile Health Tech',
 'Online Grocer',
 'Online Hotel Booking',
 'Online Kitchen Furniture',
 'Hyper-Local Online',
 'Hyper-Local Online/Mobile Grocery',
 'Ondemand Mobile Handyman',
 'Mobile Development',
 'On-Demand Handyman',
 'Beauty & Wellness Mobile',
 'Material Collection & Recycling',
 'Online Pharmacy & Drug Db',
 'Fashion Ecommerce',
 'Private Coaching Centers',
 'Online Certification Courses',
 'Ethnic Product Ecommerce',
 'Last Minute Travel Deals Mobile',
 'Usiness Expense Management',
 'Auto Rickshaw Based Logistics',
 'Spam Call Block',
 'Online Insurance Aggregator',
 'Restaurant Management',
 'Food Logistics & Delivery',
 'Interactive Educational Games',
 'Clean Tech',
 'Grey Collar Job Board',
 'Online Furniture Ecommerce',
 'Robotic Program Learning',
 'Used Gadgets Buy / Refurbishing',
 'Cloud Enterprise Software',
 'Startup Analytics',
 'Mobile Food Ordering',
 'Financial Markets Software',
 'Hiring Analytics',
 'Online Travel']

#### **Fixing the inconsistency in the 'SubVertical' column -**

In [158]:
df['SubVertical'].unique().tolist()

['App based shuttle service',
 'Retailer of baby and toddler products',
 'Online Investment',
 'Embroiled Clothes For Women',
 'Open-market, freight management platform',
 'Agritech',
 'Food Solutions For Corporate',
 'Non-Banking Financial Company',
 'Experience Discovery Platform',
 "Men's Health and Wellness brand",
 'Elearning',
 'Indian Burger Brand',
 'Healthcare services',
 'Financial Services To MSMEs',
 'Social gaming platform',
 'Electric bike rental',
 'B2B platform for medical supplies',
 'Beauty and Grooming',
 'Financial Services',
 'Invoice discounting platform and SME lending marketplace',
 'Digital marketing firm',
 'Education Technology',
 'Building automation system',
 'Deep-technology',
 'Consumer Electronics, Home Appliances',
 'Mobile-based Accounting Software',
 'Supply Chain Management',
 'Fuel Delivery',
 'Car Retail',
 'Low carb food for Diabetics',
 'Wealth Management',
 'B2B Foodtech',
 'University Admissions',
 'Product Review',
 'Auto Insurance',
 'Big Data',
 'Consulting',
 'Cabs',
 'Digital Vending Machine',
 'Logistics',
 'Smartphone Operating System',
 'Primary care medical network',
 'Clothes and Apparel',
 'Full-stack career platform',
 'Brewery',
 'FinTech',
 'Artificial Intelligence',
 'E-Books',
 'Video Platform',
 'Dockless Scooter Rental Company',
 'Digital Documentation',
 'Optimization',
 'Fashion and Shopping',
 'Retail',
 'Online Medicine',
 'Waste Management',
 'Travel',
 'Organic wellness',
 'Banking',
 'E-learning',
 'Fashion and Apparel',
 'Software Solutions',
 'Lending Platform',
 'Bus Aggregation',
 'Supply-chain technology solutions',
 'Anti-Pollution',
 'Non-banking financial company',
 'Hyperlocal Content',
 'Platform for travel agents',
 'Video-based certification, trainings',
 'eCommerce',
 'Real Estate, ERP',
 'Regional Flavours',
 'Mobile e-Sports',
 'Meat Retail Chain',
 'POS For Online Ordering',
 'Micro-delivery grocery service',
 'On-Demand Drivers',
 'Car Wash',
 'Wellness Coach',
 'Personalized Learning',
 'Art',
 'Digital Onboarding Solution',
 'Video Sharing',
 'Mens Wear',
 'Supply Chain',
 'Wine',
 'New and Used Cars Platform',
 'Co-Working',
 'Largest Trucking Platform',
 'Book Trucks Online',
 'News and ebooks Mobile App\\\\xc2\\\\xa0',
 'Healthcare Service Provider',
 'Online Travel Agecy',
 'Computer Vision And Artificial Intelligence (Ai) Platform',
 'Online Marketplace For Mother and Babycare Products',
 'Online Marketplace For Pharmaceutical Products',
 'Online Micro Lending Marketplace',
 'Personalisation Technology Firm Focusing On The Food And Beverage Industry',
 'Patient Financing Platform',
 'Social Media and Chat Entertainment Platform',
 'Online Home Rental Marketplace',
 'Holy Platform Offering Customised Puja Packages To Individuals and Corporates',
 'Online Travel Aggregator',
 'Real-time Mobile App Management',
 'Online Bike Rental Marketplace',
 'e-learning Platform',
 'Consumer Financing Platform',
 'Rural E-commerce Platform',
 'AI Based Solutions Platform',
 'Online Restaurant Table Reservation Platform',
 'Online Loan Matchmaking Platform',
 'Online Organic Juice Delivery Service',
 'Applied Artificial Intelligence and IoT focused\\\\xc2\\\\xa0Platform',
 'Online Indian Car Rental Platform',
 'Online Lending Platform',
 '\\\\xc2\\\\xa0Customer Sourcing Platform\\\\xc2\\\\xa0',
 'Local Language Health Content App',
 'Post-Purchase Customer Engagement Platform\\\\xc2\\\\xa0',
 'HR Virtual Agent For Employees',
 'Online Food Delivery',
 'E-commerce Fulfilment Platform',
 'Online Platform For Risk-Assessment Services For Real Estate Investments',
 'Online Platform That Sells Direct Plans Of Mutual Funds',
 'Online Platform That Connects Brands With Freelance Sales Professionals',
 'Med-tech Platform Providing Care For Newborns',
 'Lending Platform For Micro and Small Enterprises',
 'Mobile Storefront And Commerce Platform For Sellers',
 'Online Micro Lending Platform',
 'Artificial intelligence-based sales acceleration software platform',
 'Home diagnostics services provider',
 'A Doctor-Patient Engagement Platform',
 'Subscription-Only News Website',
 'Property Discovery Platform',
 'Online Consumer Lending Platform',
 'Bicycle-Sharing Platform',
 'Media Analytics',
 'Nanotechnology Company Specializing In Graphene',
 'Skill Learning Platform',
 'Mobile-First Video Blogging App',
 'Data Analytics Firm',
 'Software-As-A-Service Platform',
 'Travel-Focused Tech Startup',
 'Unified Global Investments Ecosystem',
 'Bus Aggregation Platform',
 'Health and Well being Platform',
 'Credit-Based Lending Marketplace For Small And Medium Enterprises',
 'Sales Analytics and Enablement Platform',
 'Online Marketplace For Handicrafts, Handlooms And Local Produce',
 'Online Crowdfunding Platform',
 'Online Healthcare Aggregator',
 'Online Marketplace For Resellers',
 'Specialised diagnostics Platform',
 'Supplychain Finance',
 'Fashion e-tailer',
 'Hyperlocal Delivery Platform',
 'An Online Platform That Connects Ayurveda Doctors With Patients',
 'Mass Market Mutual Fund Investment Platform',
 'A Local Discovery App For Dining-Out, Party, Leisure and Events',
 'Online Home Furnishing Solutions',
 'Cybersecurity Specialist',
 'Data Analytics (SaaS)',
 'Education Services Provider',
 'Online Rental Marketplace',
 'Trade Finance Firm',
 'Online Motorbike And Scooter Rental Platforms',
 'Digital Payment Platform For Beverage Delivery',
 'App-based investment platform',
 'Digital Payment Platform',
 'Data Driven Intelligence Solutions Platform',
 'E-commerce Logistics Platform',
 'An AI Platform Offering Automated Customer Service Software',
 'Online Education Platform',
 'An Artificial Intelligence-Based Recruitment Platform',
 'SaaS',
 'P2P Lending Platform',
 'AI product company For Health and Life Insurane Companies',
 'Agri-tech',
 'Doctor-Consultation App',
 'Online Video Creation Platform',
 'Micro-Delivery Grocery Startup',
 'Micro Lending Platform',
 'Products For Shoolgoing Children',
 'Housing Finance For Low-Income Families',
 'Designer Of Toys and Learning Projects For Kids',
 'Oxygen Optimiser Manufacturer',
 'Online Insurance Platform',
 'Home Healthcare Aggregator',
 'Mobile Payments Technology Platform',
 'Events and Activities Discovery Platform',
 'Iot Application Platform In Agriculture',
 'Lending Platform For SMEs',
 'Online Fitness Discovey Platform',
 'Social Media Anlaytics Platform',
 'Enhanced Employee Engagement Platform',
 'Interactive Online Tutoring Platform',
 'Digital Financial Services Platform',
 'Fashion Accessories Etailer',
 'Blockchain Platform',
 'Mobile-Based Education Network',
 'Digital Lending Platform In Logistics',
 'Online Travel Marketplace',
 'Platform To Discover Healthcare Financing Options',
 'Online Platform For Luxury Hotel Stay For Business Travelers',
 'Connected Care App For Pregnant Women',
 'Online Eyewear Retailer',
 'Online Baby care Products',
 'AI Based Expense Management Platform',
 'AI Driven Health tech Platform',
 'Digitized Health-Tech Solutions For Practitioners',
 'Beauty e-tailer',
 'Online Platform Providing Micro Loans For Air Travel',
 'Women Focussed Digital Media Platform',
 'Online Travel Ticketing Platform',
 'Online Pharmacy Store',
 'Online Lending MarketPlace',
 'Online Stock Broker',
 'B2C Online Loans Marketplace',
 'Online Scholarship Portal',
 'Online Furniture Store',
 'Online Financial Planning',
 'Therapeutics',
 'Genetic Screening, DNA Diagnostics Labs & Research Centers',
 'Online Lending',
 'Cloud based Online Hotel Management Software',
 'Health Service Aggregator Platform',
 'Creative Design, Brand, Media and Technology Platform Solutions',
 'Online Insurance Aggregator',
 'Hyperlocal Discovery',
 'Healthcare Aggregator',
 'Online Communication and Collaboration Platform For Educational Institutions',
 'Ready To cook Food Solution',
 'Technology enabled equitable healthcare for India',
 'Online Raw Meat E-tailer',
 'Customer Success Software for B2B SaaS',
 'Micro Jobs Provider For Students',
 'Subscription Billing & Recurring Payments Software',
 'Online loan platform',
 'Voice-based assistant platform',
 'Online ordering solution for restaurants and food chains',
 'Fleet management and asset monitoring platform',
 'Micro lending company',
 'News portal',
 'Professional Car Drivers Hiring App',
 'O2O fashion ecommerce platform',
 'E-Publishing',
 'Online platform for Higher Education Services',
 'Online Food Marketplace',
 'Preventive Health Checkup',
 'Mobile Weight Loss Coach',
 'Virtual health clinics',
 'Online Gold Loan',
 'Marketing Cloud for consumer businesses',
 'B2B Marketplace',
 'Online Selling',
 'Mobile Solutions for Social Impact',
 'Individualised Progressive Learning Program',
 'Integrated Kids Engagement Company',
 'mobile payment platform',
 'Online Pet Care Products',
 'Online Retailing',
 'Expense Management',
 'Fin-Tech',
 'Analytics',
 'Cloud-based Software',
 'Education',
 'Robotic InspectionStartup',
 'Digital Design',
 'AI platform for hospitality industry',
 'Cancer radiology',
 'Mobile App Analytics',
 'Food and Beverages',
 'Sports Nutrition Supplement etailer',
 'Digital Entertainment for Children',
 'Personal Assistant',
 'Algorithmic Trading',
 'Social',
 'IT',
 'Artificial Intellegence',
 'Alternative Lending',
 'Online Grocery',
 'Coaching Services',
 'Eyewear',
 'Hemostatic Dressing Solutions',
 'Technology',
 'Online Services',
 'Hygiene',
 'Virtual Reality',
 'Mobile Payment Platform',
 'Fitness',
 'Education Solutions',
 'IoT based air pollution controller',
 'Daily Task Management Mobile App',
 'Mobile Learning Management Platform',
 'Bicycle sharing Platform',
 'Child Learning & Development Platform',
 'Mobile point of sale services provider',
 'Home Decor and Online Fashion Portal',
 'Super speciality Hospitals',
 '"Women\\\\\'s Fashion Clothing Online Platform"',
 'Mobile News Curation App',
 'Online Platform Selling Indian Tea Globally',
 'Educational Platform to Learn Mathematics',
 'Assisting Visually Impaired to learn through Braille',
 'Furniture Rental Platform',
 'Hotel Aggregator Platform',
 'Platform based on 3D printing and Digital Manufacturing',
 'Adaptive Fraud Intelligence Platform',
 'Fashion and Lifestyle Coupon Platform',
 'Mobile Application for Doctor Consultation',
 'Artificial Intelligence Platform to Raise Funds',
 'Fresh Indian Tea Selling Platform across 112 countries',
 'Hyperlocal Video Information Sharing Platform',
 'Mobile App for Network of Doctors',
 'Online Furniture Marketplace',
 'Provides Business Insights using Drone Imaginary',
 'Beauty Products Online Marketplace',
 'Online Micro-Lending Platform',
 'Weather Forecast Platform',
 'Online Courses and Mentoring from Experts',
 'SaaS based Big Data Analytics Platform',
 'Online Poker Platform',
 'Vernacular and Video Content Platform',
 'Regional Operating System for Smartphones',
 'Ecommerce enabler platform',
 'Online Gifting Platform',
 'Online Spects Platform for Men and Women',
 'Online vehicle service booking platform',
 'Realty Tech Startup solving real life Interior Designing problems',
 'Business & SME Loans provider',
 'Aadhaar-based API provider',
 'Online Grocery Store',
 'Online Tutorial Marketplace',
 'Online Fantasy Games',
 'VR based Spiritual platform',
 'Real time data analytics & reporting',
 'Financial Technology Research Platform',
 'Customer Engagement Platform',
 'Doctor Patient Communication platform',
 'Wearable tech and Internet of Things platform',
 'Distance Education Learning Platform',
 'Mutual Fund Investment App',
 'Online platform for Agricultural products',
 'IoT based Tech Startup',
 'Enrolment Management Platform',
 'Saas based Corporate Travel Management Solution',
 'Augmented Reality based Tech platform',
 'Online Gifting platform',
 'Celebrity fashion accessories and merchandise',
 'Healthy & Nutrition based snacks online platform',
 'AI based FinTech platform',
 'Banking Software License Platform',
 'Social Healthcare Enterprise',
 'WiFi Analytics Platform',
 'Storytelling platform',
 'End-to-End property management for landlords living away',
 'Placement preparation and career growth training platform',
 'Self riding bike rental program',
 'Bike and Taxi pooling online platform',
 'Big Data Analytics Platform',
 'Managed Cloud Environment Solutions',
 'AI based pharmacy drugs insights platform',
 'Vehicle loan approval platform',
 'Online Hotel Reservation Platform',
 'Viral Content and storytelling platform',
 'Venture Capitalist',
 'IoT and SaaS based transportation platform',
 'Identity management platform',
 'Virtual Reality based gaming platform',
 'Designer-led consumer products',
 'Online Truck aggregator platform',
 'Health and fitness based mobile App',
 'Student accommodation platform',
 'Home Loans Aggregation platform',
 'Home Loan Down payment assistance program',
 'P2P platform for Fashion sales',
 'Education collaboration platform',
 'Local Recommendations and Discoveries Platform',
 'rooftop solar platform',
 'Ecommerce Portal for Used Goods',
 'Mobile repair and Refurbishment platform',
 'Fresh Produce SCM company',
 'Self Drive car and bike rental platform',
 'Student Micro-financing platform',
 'Agriculture Supply Chain management solutions',
 'Home Interior Designing Seller',
 'Treasury Risk Management Solution',
 'Auto Service Logistics & SAAS platform',
 'Education Technology platform',
 'AI-powered anti-fraud solutions',
 'AI-powered deep learning solutions',
 'online restaurant reservation platform',
 'Online Reseller Network',
 'Medical Transportation Services',
 'Education Network for Institutions, teachers & Students',
 'home maintenance services platform',
 'Online Chai ordering platform',
 'Micro-lending platform',
 'Food Ordering Portal',
 'Online Financial Marketplace',
 'App building platform',
 'B2B Logistics provider',
 'Online peer-to-peer lending platform',
 'Mobile based learning app',
 'Cold pressed Juice maker',
 'app-only lending platform',
 'Machine learning based parking discovery',
 'Cold Chain monitoring solution',
 'Herbal energy shot maker',
 'SME lending platform',
 'Online Learning Platform',
 'Frozen Meat provider',
 'Real Estate content portal',
 'Contract Automation',
 'Online Grocery portal',
 'B2B Finance & Fulfilment Network',
 'Credit + payment mobile app',
 'Payments Platform for Marketplaces and Fintechs',
 'App based cab hailing services',
 'Agriculture Technology',
 'Online Pharmacy',
 'Online B2B store for office supplies',
 'Online Doctor Discovery platform',
 'Online Photography platform',
 'Application Performance Acceleration',
 'online lending platform',
 'EduTech Platform',
 'Online travel booking platform',
 'Medical Diagnostic Solutions',
 'Online Credit scoring platform',
 'Pet care portal & mobile app',
 'Online Unsecured Lending platform',
 'online babycare products marketplace',
 'Ecommerce portal for senior citizens',
 'Agre-Tech Mobile app',
 'Healthcare Services Aggregator',
 'Health Food etailer',
 'Healthcare services portal',
 'Imaging Technology for Armed Forces',
 'Smart Parking Enabler',
 'Content marketing platform',
 'women focussed customer-to-customer reseller network',
 'udget hotel marketplace',
 'Online learning platform',
 'Telecom & IoT platform',
 'co-working space provider',
 'Bike Rental Platform',
 'Online Tutoring Platform',
 'Pregnancy & Baby Care product etailer',
 'mobile-first communication platform for on-field staff,',
 'Technology-Empowered Healthcare Solutions',
 'financial services firm',
 'E-sports platform',
 'Co-working spaces',
 'Home Furnishing & Building material marketplace',
 'Online Travel Agency',
 'Omni-channel web commerce solutions provider',
 'Scooter Rental Platform',
 'SME Marketing Management Solution',
 'Food Delivery platform',
 'Crop Technology Solutions',
 'Bike Aggregator Mobile App',
 'Sports & Sport related equipment portal',
 'Online consumer lending platform',
 'Matchmaking app for the differently abled',
 'Language learning Mobile App',
 'Geospatial Technology-based SaaS solutions',
 'O2O fashion discovery platform',
 'Car repair and Servicing Platform',
 'Luxury Helicopter Tourism Services portal',
 'Local Language Health Information portal',
 'Defense Tech & Aerospace startup',
 'Predictive Care Platform',
 'Digital Marketing Agency',
 'DIY Ecommerce platform',
 'healthcare service aggregator',
 'On-Demand Logistics Service provider',
 'Recruitment Portal',
 'Tea Delivery Portal & offline stores',
 'Health Products & Services Aggregator',
 'Restaurant Management Solutions',
 'Fashion Resale Marketplace',
 'Warehouse Aggregator',
 'Skincare Speciality services',
 'Hospital Management Software',
 'foreign exchange services',
 'Mobile based Logistics Service',
 'Agriculture Supply Chain solutions',
 'Online milk delivery',
 'Co-Living space aggregator',
 'Mobile games developer',
 'Sports Content Mobile App',
 'Personal Loans & EMI solutions platform',
 'Unsecured Small Business Loans',
 'Payment Solution Mobile app',
 'Building material online store',
 'speech recognition startup',
 'E-Tech platform',
 'instant messaging platform',
 'Govt service application portal',
 'Online Grocery platform',
 'Men Grooming product etailer',
 'Operations and manpower outsourcing',
 'Software & Mobile app development platform',
 'mPOS solutions provider',
 'Online printing marketplace',
 'Online Doctor Discovery Platform',
 'Restaurant & Hotel CRM platform',
 'Healthtech IoT platform',
 'SAAS based sales force automation services',
 'Peer to Peer Lending platform',
 'Energy management solutions provider',
 'online marketplace for food and grocery',
 'B2B marketplace for Industrial products',
 'Hyperlocal home services provider',
 'Cloud Solutions provider',
 'parenting blog and kids\\\\xe2\\\\x80\\\\x99 events discovery platform',
 'Digital Media Video platform',
 'MF investment platform',
 'Workshop Management Software Platform',
 'Salon & Spa Aggregation & Discovery platform',
 'Video Content Discovery Platform',
 'Online Interior Design platform',
 'Digital payments solutions',
 'Door Step Delivery platform',
 'Chatbot creation tool',
 'Next Gen Mobility device manufacturer',
 'Construction site operations and analytics platform',
 'Designer consumer products Marketplace',
 'Sales Solutions for Fashion Brands',
 'Enterprise Banking Solutions',
 'Mobile Services & Solutions',
 'Ambulance Aggregation Services',
 'Online Insurance platform',
 'Mobile games creator',
 'Consumer Leasing Platform',
 'AI powered recruitment platform',
 'Gamified Learning App',
 'Online payments platform',
 'Online Marketplace for Construction Material',
 'Women Work wear etailer',
 'Machine Learning Access platform',
 'Healthy Food Delivery Platform',
 'Mobile-first Enterprise communication platform',
 'Co-Working Space Provider',
 'Assisted Learning Startup',
 'App-based Aggregator of Offline Businesses',
 'Beauty Services Marketplace',
 'online marketplace for discovering fitness centres',
 'Mobile based travel ERP platform',
 'Online Marketplace for Renting Bikes, Electronics & Appliances',
 'Online Wealth Management & Savings platform',
 'Online Used Car marketplace',
 'Healthcare Discovery & booking platform',
 'Mobile Payments platform',
 'co-working spaces',
 'Mobile app for Mental Health',
 'Education Marketplace',
 'For profit Social Venture',
 'Online lending platform',
 'health and fitness discovery platform',
 'Health coaching programs',
 'CRM Software for Healthcare space',
 'Unified Digital Health Platform',
 'App-based Investment advisory Services',
 'Travel & adventure planning platform',
 'ambulance aggregator and medical taxi provider',
 'Online Lending platform',
 'Hygiene care product manufacturer',
 'Online rooms aggregation platform',
 'Online insurance brokerage platform',
 'Location tracking solutions',
 'CSR and sustainability management platform',
 'Tech driven Insurance platform',
 'Beauty products discovery platform',
 'Micro Food Delivery platform',

In [159]:
# 1. Fix the broken apostrophe (\\\\xe2\\\\x80\\\\x99)
df['SubVertical'] = df['SubVertical'].str.replace(r'\\\\xe2\\\\x80\\\\x99', "'", regex=True)

# 2. Fix the broken space junk (\\\\xc2\\\\xa0) from previous examples
df['SubVertical'] = df['SubVertical'].str.replace(r'\\\\xc2\\\\xa0', ' ', regex=True)

# 3. Standardize casing and trim extra whitespace
df['SubVertical'] = df['SubVertical'].str.title().str.strip()

In [160]:
df['SubVertical'].unique().tolist()

['App Based Shuttle Service',
 'Retailer Of Baby And Toddler Products',
 'Online Investment',
 'Embroiled Clothes For Women',
 'Open-Market, Freight Management Platform',
 'Agritech',
 'Food Solutions For Corporate',
 'Non-Banking Financial Company',
 'Experience Discovery Platform',
 "Men'S Health And Wellness Brand",
 'Elearning',
 'Indian Burger Brand',
 'Healthcare Services',
 'Financial Services To Msmes',
 'Social Gaming Platform',
 'Electric Bike Rental',
 'B2B Platform For Medical Supplies',
 'Beauty And Grooming',
 'Financial Services',
 'Invoice Discounting Platform And Sme Lending Marketplace',
 'Digital Marketing Firm',
 'Education Technology',
 'Building Automation System',
 'Deep-Technology',
 'Consumer Electronics, Home Appliances',
 'Mobile-Based Accounting Software',
 'Supply Chain Management',
 'Fuel Delivery',
 'Car Retail',
 'Low Carb Food For Diabetics',
 'Wealth Management',
 'B2B Foodtech',
 'University Admissions',
 'Product Review',
 'Auto Insurance',
 'Big Data',
 'Consulting',
 'Cabs',
 'Digital Vending Machine',
 'Logistics',
 'Smartphone Operating System',
 'Primary Care Medical Network',
 'Clothes And Apparel',
 'Full-Stack Career Platform',
 'Brewery',
 'Fintech',
 'Artificial Intelligence',
 'E-Books',
 'Video Platform',
 'Dockless Scooter Rental Company',
 'Digital Documentation',
 'Optimization',
 'Fashion And Shopping',
 'Retail',
 'Online Medicine',
 'Waste Management',
 'Travel',
 'Organic Wellness',
 'Banking',
 'E-Learning',
 'Fashion And Apparel',
 'Software Solutions',
 'Lending Platform',
 'Bus Aggregation',
 'Supply-Chain Technology Solutions',
 'Anti-Pollution',
 'Hyperlocal Content',
 'Platform For Travel Agents',
 'Video-Based Certification, Trainings',
 'Ecommerce',
 'Real Estate, Erp',
 'Regional Flavours',
 'Mobile E-Sports',
 'Meat Retail Chain',
 'Pos For Online Ordering',
 'Micro-Delivery Grocery Service',
 'On-Demand Drivers',
 'Car Wash',
 'Wellness Coach',
 'Personalized Learning',
 'Art',
 'Digital Onboarding Solution',
 'Video Sharing',
 'Mens Wear',
 'Supply Chain',
 'Wine',
 'New And Used Cars Platform',
 'Co-Working',
 'Largest Trucking Platform',
 'Book Trucks Online',
 'News And Ebooks Mobile App',
 'Healthcare Service Provider',
 'Online Travel Agecy',
 'Computer Vision And Artificial Intelligence (Ai) Platform',
 'Online Marketplace For Mother And Babycare Products',
 'Online Marketplace For Pharmaceutical Products',
 'Online Micro Lending Marketplace',
 'Personalisation Technology Firm Focusing On The Food And Beverage Industry',
 'Patient Financing Platform',
 'Social Media And Chat Entertainment Platform',
 'Online Home Rental Marketplace',
 'Holy Platform Offering Customised Puja Packages To Individuals And Corporates',
 'Online Travel Aggregator',
 'Real-Time Mobile App Management',
 'Online Bike Rental Marketplace',
 'E-Learning Platform',
 'Consumer Financing Platform',
 'Rural E-Commerce Platform',
 'Ai Based Solutions Platform',
 'Online Restaurant Table Reservation Platform',
 'Online Loan Matchmaking Platform',
 'Online Organic Juice Delivery Service',
 'Applied Artificial Intelligence And Iot Focused Platform',
 'Online Indian Car Rental Platform',
 'Online Lending Platform',
 'Customer Sourcing Platform',
 'Local Language Health Content App',
 'Post-Purchase Customer Engagement Platform',
 'Hr Virtual Agent For Employees',
 'Online Food Delivery',
 'E-Commerce Fulfilment Platform',
 'Online Platform For Risk-Assessment Services For Real Estate Investments',
 'Online Platform That Sells Direct Plans Of Mutual Funds',
 'Online Platform That Connects Brands With Freelance Sales Professionals',
 'Med-Tech Platform Providing Care For Newborns',
 'Lending Platform For Micro And Small Enterprises',
 'Mobile Storefront And Commerce Platform For Sellers',
 'Online Micro Lending Platform',
 'Artificial Intelligence-Based Sales Acceleration Software Platform',
 'Home Diagnostics Services Provider',
 'A Doctor-Patient Engagement Platform',
 'Subscription-Only News Website',
 'Property Discovery Platform',
 'Online Consumer Lending Platform',
 'Bicycle-Sharing Platform',
 'Media Analytics',
 'Nanotechnology Company Specializing In Graphene',
 'Skill Learning Platform',
 'Mobile-First Video Blogging App',
 'Data Analytics Firm',
 'Software-As-A-Service Platform',
 'Travel-Focused Tech Startup',
 'Unified Global Investments Ecosystem',
 'Bus Aggregation Platform',
 'Health And Well Being Platform',
 'Credit-Based Lending Marketplace For Small And Medium Enterprises',
 'Sales Analytics And Enablement Platform',
 'Online Marketplace For Handicrafts, Handlooms And Local Produce',
 'Online Crowdfunding Platform',
 'Online Healthcare Aggregator',
 'Online Marketplace For Resellers',
 'Specialised Diagnostics Platform',
 'Supplychain Finance',
 'Fashion E-Tailer',
 'Hyperlocal Delivery Platform',
 'An Online Platform That Connects Ayurveda Doctors With Patients',
 'Mass Market Mutual Fund Investment Platform',
 'A Local Discovery App For Dining-Out, Party, Leisure And Events',
 'Online Home Furnishing Solutions',
 'Cybersecurity Specialist',
 'Data Analytics (Saas)',
 'Education Services Provider',
 'Online Rental Marketplace',
 'Trade Finance Firm',
 'Online Motorbike And Scooter Rental Platforms',
 'Digital Payment Platform For Beverage Delivery',
 'App-Based Investment Platform',
 'Digital Payment Platform',
 'Data Driven Intelligence Solutions Platform',
 'E-Commerce Logistics Platform',
 'An Ai Platform Offering Automated Customer Service Software',
 'Online Education Platform',
 'An Artificial Intelligence-Based Recruitment Platform',
 'Saas',
 'P2P Lending Platform',
 'Ai Product Company For Health And Life Insurane Companies',
 'Agri-Tech',
 'Doctor-Consultation App',
 'Online Video Creation Platform',
 'Micro-Delivery Grocery Startup',
 'Micro Lending Platform',
 'Products For Shoolgoing Children',
 'Housing Finance For Low-Income Families',
 'Designer Of Toys And Learning Projects For Kids',
 'Oxygen Optimiser Manufacturer',
 'Online Insurance Platform',
 'Home Healthcare Aggregator',
 'Mobile Payments Technology Platform',
 'Events And Activities Discovery Platform',
 'Iot Application Platform In Agriculture',
 'Lending Platform For Smes',
 'Online Fitness Discovey Platform',
 'Social Media Anlaytics Platform',
 'Enhanced Employee Engagement Platform',
 'Interactive Online Tutoring Platform',
 'Digital Financial Services Platform',
 'Fashion Accessories Etailer',
 'Blockchain Platform',
 'Mobile-Based Education Network',
 'Digital Lending Platform In Logistics',
 'Online Travel Marketplace',
 'Platform To Discover Healthcare Financing Options',
 'Online Platform For Luxury Hotel Stay For Business Travelers',
 'Connected Care App For Pregnant Women',
 'Online Eyewear Retailer',
 'Online Baby Care Products',
 'Ai Based Expense Management Platform',
 'Ai Driven Health Tech Platform',
 'Digitized Health-Tech Solutions For Practitioners',
 'Beauty E-Tailer',
 'Online Platform Providing Micro Loans For Air Travel',
 'Women Focussed Digital Media Platform',
 'Online Travel Ticketing Platform',
 'Online Pharmacy Store',
 'Online Lending Marketplace',
 'Online Stock Broker',
 'B2C Online Loans Marketplace',
 'Online Scholarship Portal',
 'Online Furniture Store',
 'Online Financial Planning',
 'Therapeutics',
 'Genetic Screening, Dna Diagnostics Labs & Research Centers',
 'Online Lending',
 'Cloud Based Online Hotel Management Software',
 'Health Service Aggregator Platform',
 'Creative Design, Brand, Media And Technology Platform Solutions',
 'Online Insurance Aggregator',
 'Hyperlocal Discovery',
 'Healthcare Aggregator',
 'Online Communication And Collaboration Platform For Educational Institutions',
 'Ready To Cook Food Solution',
 'Technology Enabled Equitable Healthcare For India',
 'Online Raw Meat E-Tailer',
 'Customer Success Software For B2B Saas',
 'Micro Jobs Provider For Students',
 'Subscription Billing & Recurring Payments Software',
 'Online Loan Platform',
 'Voice-Based Assistant Platform',
 'Online Ordering Solution For Restaurants And Food Chains',
 'Fleet Management And Asset Monitoring Platform',
 'Micro Lending Company',
 'News Portal',
 'Professional Car Drivers Hiring App',
 'O2O Fashion Ecommerce Platform',
 'E-Publishing',
 'Online Platform For Higher Education Services',
 'Online Food Marketplace',
 'Preventive Health Checkup',
 'Mobile Weight Loss Coach',
 'Virtual Health Clinics',
 'Online Gold Loan',
 'Marketing Cloud For Consumer Businesses',
 'B2B Marketplace',
 'Online Selling',
 'Mobile Solutions For Social Impact',
 'Individualised Progressive Learning Program',
 'Integrated Kids Engagement Company',
 'Mobile Payment Platform',
 'Online Pet Care Products',
 'Online Retailing',
 'Expense Management',
 'Fin-Tech',
 'Analytics',
 'Cloud-Based Software',
 'Education',
 'Robotic Inspectionstartup',
 'Digital Design',
 'Ai Platform For Hospitality Industry',
 'Cancer Radiology',
 'Mobile App Analytics',
 'Food And Beverages',
 'Sports Nutrition Supplement Etailer',
 'Digital Entertainment For Children',
 'Personal Assistant',
 'Algorithmic Trading',
 'Social',
 'It',
 'Artificial Intellegence',
 'Alternative Lending',
 'Online Grocery',
 'Coaching Services',
 'Eyewear',
 'Hemostatic Dressing Solutions',
 'Technology',
 'Online Services',
 'Hygiene',
 'Virtual Reality',
 'Fitness',
 'Education Solutions',
 'Iot Based Air Pollution Controller',
 'Daily Task Management Mobile App',
 'Mobile Learning Management Platform',
 'Bicycle Sharing Platform',
 'Child Learning & Development Platform',
 'Mobile Point Of Sale Services Provider',
 'Home Decor And Online Fashion Portal',
 'Super Speciality Hospitals',
 '"Women\\\\\'S Fashion Clothing Online Platform"',
 'Mobile News Curation App',
 'Online Platform Selling Indian Tea Globally',
 'Educational Platform To Learn Mathematics',
 'Assisting Visually Impaired To Learn Through Braille',
 'Furniture Rental Platform',
 'Hotel Aggregator Platform',
 'Platform Based On 3D Printing And Digital Manufacturing',
 'Adaptive Fraud Intelligence Platform',
 'Fashion And Lifestyle Coupon Platform',
 'Mobile Application For Doctor Consultation',
 'Artificial Intelligence Platform To Raise Funds',
 'Fresh Indian Tea Selling Platform Across 112 Countries',
 'Hyperlocal Video Information Sharing Platform',
 'Mobile App For Network Of Doctors',
 'Online Furniture Marketplace',
 'Provides Business Insights Using Drone Imaginary',
 'Beauty Products Online Marketplace',
 'Online Micro-Lending Platform',
 'Weather Forecast Platform',
 'Online Courses And Mentoring From Experts',
 'Saas Based Big Data Analytics Platform',
 'Online Poker Platform',
 'Vernacular And Video Content Platform',
 'Regional Operating System For Smartphones',
 'Ecommerce Enabler Platform',
 'Online Gifting Platform',
 'Online Spects Platform For Men And Women',
 'Online Vehicle Service Booking Platform',
 'Realty Tech Startup Solving Real Life Interior Designing Problems',
 'Business & Sme Loans Provider',
 'Aadhaar-Based Api Provider',
 'Online Grocery Store',
 'Online Tutorial Marketplace',
 'Online Fantasy Games',
 'Vr Based Spiritual Platform',
 'Real Time Data Analytics & Reporting',
 'Financial Technology Research Platform',
 'Customer Engagement Platform',
 'Doctor Patient Communication Platform',
 'Wearable Tech And Internet Of Things Platform',
 'Distance Education Learning Platform',
 'Mutual Fund Investment App',
 'Online Platform For Agricultural Products',
 'Iot Based Tech Startup',
 'Enrolment Management Platform',
 'Saas Based Corporate Travel Management Solution',
 'Augmented Reality Based Tech Platform',
 'Celebrity Fashion Accessories And Merchandise',
 'Healthy & Nutrition Based Snacks Online Platform',
 'Ai Based Fintech Platform',
 'Banking Software License Platform',
 'Social Healthcare Enterprise',
 'Wifi Analytics Platform',
 'Storytelling Platform',
 'End-To-End Property Management For Landlords Living Away',
 'Placement Preparation And Career Growth Training Platform',
 'Self Riding Bike Rental Program',
 'Bike And Taxi Pooling Online Platform',
 'Big Data Analytics Platform',
 'Managed Cloud Environment Solutions',
 'Ai Based Pharmacy Drugs Insights Platform',
 'Vehicle Loan Approval Platform',
 'Online Hotel Reservation Platform',
 'Viral Content And Storytelling Platform',
 'Venture Capitalist',
 'Iot And Saas Based Transportation Platform',
 'Identity Management Platform',
 'Virtual Reality Based Gaming Platform',
 'Designer-Led Consumer Products',
 'Online Truck Aggregator Platform',
 'Health And Fitness Based Mobile App',
 'Student Accommodation Platform',
 'Home Loans Aggregation Platform',
 'Home Loan Down Payment Assistance Program',
 'P2P Platform For Fashion Sales',
 'Education Collaboration Platform',
 'Local Recommendations And Discoveries Platform',
 'Rooftop Solar Platform',
 'Ecommerce Portal For Used Goods',
 'Mobile Repair And Refurbishment Platform',
 'Fresh Produce Scm Company',
 'Self Drive Car And Bike Rental Platform',
 'Student Micro-Financing Platform',
 'Agriculture Supply Chain Management Solutions',
 'Home Interior Designing Seller',
 'Treasury Risk Management Solution',
 'Auto Service Logistics & Saas Platform',
 'Education Technology Platform',
 'Ai-Powered Anti-Fraud Solutions',
 'Ai-Powered Deep Learning Solutions',
 'Online Restaurant Reservation Platform',
 'Online Reseller Network',
 'Medical Transportation Services',
 'Education Network For Institutions, Teachers & Students',
 'Home Maintenance Services Platform',
 'Online Chai Ordering Platform',
 'Micro-Lending Platform',
 'Food Ordering Portal',
 'Online Financial Marketplace',
 'App Building Platform',
 'B2B Logistics Provider',
 'Online Peer-To-Peer Lending Platform',
 'Mobile Based Learning App',
 'Cold Pressed Juice Maker',
 'App-Only Lending Platform',
 'Machine Learning Based Parking Discovery',
 'Cold Chain Monitoring Solution',
 'Herbal Energy Shot Maker',
 'Sme Lending Platform',
 'Online Learning Platform',
 'Frozen Meat Provider',
 'Real Estate Content Portal',
 'Contract Automation',
 'Online Grocery Portal',
 'B2B Finance & Fulfilment Network',
 'Credit + Payment Mobile App',
 'Payments Platform For Marketplaces And Fintechs',
 'App Based Cab Hailing Services',
 'Agriculture Technology',
 'Online Pharmacy',
 'Online B2B Store For Office Supplies',
 'Online Doctor Discovery Platform',
 'Online Photography Platform',
 'Application Performance Acceleration',
 'Edutech Platform',
 'Online Travel Booking Platform',
 'Medical Diagnostic Solutions',
 'Online Credit Scoring Platform',
 'Pet Care Portal & Mobile App',
 'Online Unsecured Lending Platform',
 'Online Babycare Products Marketplace',
 'Ecommerce Portal For Senior Citizens',
 'Agre-Tech Mobile App',
 'Healthcare Services Aggregator',
 'Health Food Etailer',
 'Healthcare Services Portal',
 'Imaging Technology For Armed Forces',
 'Smart Parking Enabler',
 'Content Marketing Platform',
 'Women Focussed Customer-To-Customer Reseller Network',
 'Udget Hotel Marketplace',
 'Telecom & Iot Platform',
 'Co-Working Space Provider',
 'Bike Rental Platform',
 'Online Tutoring Platform',
 'Pregnancy & Baby Care Product Etailer',
 'Mobile-First Communication Platform For On-Field Staff,',
 'Technology-Empowered Healthcare Solutions',
 'Financial Services Firm',
 'E-Sports Platform',
 'Co-Working Spaces',
 'Home Furnishing & Building Material Marketplace',
 'Online Travel Agency',
 'Omni-Channel Web Commerce Solutions Provider',
 'Scooter Rental Platform',
 'Sme Marketing Management Solution',
 'Food Delivery Platform',
 'Crop Technology Solutions',
 'Bike Aggregator Mobile App',
 'Sports & Sport Related Equipment Portal',
 'Matchmaking App For The Differently Abled',
 'Language Learning Mobile App',
 'Geospatial Technology-Based Saas Solutions',
 'O2O Fashion Discovery Platform',
 'Car Repair And Servicing Platform',
 'Luxury Helicopter Tourism Services Portal',
 'Local Language Health Information Portal',
 'Defense Tech & Aerospace Startup',
 'Predictive Care Platform',
 'Digital Marketing Agency',
 'Diy Ecommerce Platform',
 'Healthcare Service Aggregator',
 'On-Demand Logistics Service Provider',
 'Recruitment Portal',
 'Tea Delivery Portal & Offline Stores',
 'Health Products & Services Aggregator',
 'Restaurant Management Solutions',
 'Fashion Resale Marketplace',
 'Warehouse Aggregator',
 'Skincare Speciality Services',
 'Hospital Management Software',
 'Foreign Exchange Services',
 'Mobile Based Logistics Service',
 'Agriculture Supply Chain Solutions',
 'Online Milk Delivery',
 'Co-Living Space Aggregator',
 'Mobile Games Developer',
 'Sports Content Mobile App',
 'Personal Loans & Emi Solutions Platform',
 'Unsecured Small Business Loans',
 'Payment Solution Mobile App',
 'Building Material Online Store',
 'Speech Recognition Startup',
 'E-Tech Platform',
 'Instant Messaging Platform',
 'Govt Service Application Portal',
 'Online Grocery Platform',
 'Men Grooming Product Etailer',
 'Operations And Manpower Outsourcing',
 'Software & Mobile App Development Platform',
 'Mpos Solutions Provider',
 'Online Printing Marketplace',
 'Restaurant & Hotel Crm Platform',
 'Healthtech Iot Platform',
 'Saas Based Sales Force Automation Services',
 'Peer To Peer Lending Platform',
 'Energy Management Solutions Provider',
 'Online Marketplace For Food And Grocery',
 'B2B Marketplace For Industrial Products',
 'Hyperlocal Home Services Provider',
 'Cloud Solutions Provider',
 "Parenting Blog And Kids' Events Discovery Platform",
 'Digital Media Video Platform',
 'Mf Investment Platform',
 'Workshop Management Software Platform',
 'Salon & Spa Aggregation & Discovery Platform',
 'Video Content Discovery Platform',
 'Online Interior Design Platform',
 'Digital Payments Solutions',
 'Door Step Delivery Platform',
 'Chatbot Creation Tool',
 'Next Gen Mobility Device Manufacturer',
 'Construction Site Operations And Analytics Platform',
 'Designer Consumer Products Marketplace',
 'Sales Solutions For Fashion Brands',
 'Enterprise Banking Solutions',
 'Mobile Services & Solutions',
 'Ambulance Aggregation Services',
 'Mobile Games Creator',
 'Consumer Leasing Platform',
 'Ai Powered Recruitment Platform',
 'Gamified Learning App',
 'Online Payments Platform',
 'Online Marketplace For Construction Material',
 'Women Work Wear Etailer',
 'Machine Learning Access Platform',
 'Healthy Food Delivery Platform',
 'Mobile-First Enterprise Communication Platform',
 'Assisted Learning Startup',
 'App-Based Aggregator Of Offline Businesses',
 'Beauty Services Marketplace',
 'Online Marketplace For Discovering Fitness Centres',
 'Mobile Based Travel Erp Platform',
 'Online Marketplace For Renting Bikes, Electronics & Appliances',
 'Online Wealth Management & Savings Platform',
 'Online Used Car Marketplace',
 'Healthcare Discovery & Booking Platform',
 'Mobile Payments Platform',
 'Mobile App For Mental Health',
 'Education Marketplace',
 'For Profit Social Venture',
 'Health And Fitness Discovery Platform',
 'Health Coaching Programs',
 'Crm Software For Healthcare Space',
 'Unified Digital Health Platform',
 'App-Based Investment Advisory Services',
 'Travel & Adventure Planning Platform',
 'Ambulance Aggregator And Medical Taxi Provider',
 'Hygiene Care Product Manufacturer',
 'Online Rooms Aggregation Platform',
 'Online Insurance Brokerage Platform',
 'Location Tracking Solutions',
 'Csr And Sustainability Management Platform',
 'Tech Driven Insurance Platform',
 'Beauty Products Discovery Platform',
 'Micro Food Delivery Platform',
 'Money Lending Platform',
 'Mobile Saas  Ecommerce Platform For Smes',
 'Personal Finance Platform',
 'Maritime Solutions',
 'Diy Project Kits Seller',
 'Cloud-Based Product Discovery Platform',
 'Enterprise Human Resources Management Platform',
 'Mobile Based Ecommerce Platform',
 'Events Ticketing Platform',
 'Fashion Etailer',
 'Health-Tech Platform',
 'Artificial Intelligence Based Platform',
 'Credit Card Fraud Protection',

In [ ]:
#### **Fixing the inconsistency in the 'Round' column -**

In [ ]:
df['Round'].unique().tolist()

In [162]:
  Mapping={
    # Pre-Series A
    'Pre-Series A': 'Pre-Series A',
    'Pre Series A': 'Pre-Series A',
    'Pre-Series A ': 'Pre-Series A',

    # Debt
    'Debt Funding': 'Debt',
    'Debt-Funding': 'Debt'}

In [166]:
df['Round']=df['Round'].replace('Mapping')

/tmp/ipykernel_57/2861844759.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['Round']=df['Round'].replace('Mapping')

In [167]:
df['Round'].str.replace('Funding','').str.replace('Round','').str.replace('Equity','').str.strip().str.title().unique()

array(['Series C', 'Series B', 'Pre-Series A', 'Seed', 'Series A', 'Debt',
       'Venture', 'Corporate', 'Maiden', 'Private', 'Series D', 'Angel',
       'Series J', 'Venture - Series Unknown', 'Bridge',
       'Debt And Preference Capital', 'Inhouse', 'Seed/ Angel',
       'Pre Series A', 'Debt-', '', 'Mezzanine', 'Series B (Extension)',
       'Series E', 'Seed / Angel', 'Seed/Angel', 'Seed Funding',
       'Seed / Angle', 'Angel / Seed', 'Structured Debt', 'Term Loan'],
      dtype=object)

#### **Fixing the inconsistency in the 'Investors' column -**

In [ ]:
df['Investors'].unique().tolist()

I am using a dual-dataframe approach to handle rows with multiple Investors name 
The dataset contains multiple investor names in a single row separated by commas.  
To perform proper investor-level analysis, a separate dataframe was created.

- `df_original` is used for:
  - Funding analysis
  - Sector analysis
  - City analysis
  - Startup analysis

- `df_investor` is used for:
  - Investor analysis
  - Top investors
  - Investor participation trends

In [ ]:
df['Investors']=df['Investors'].str.replace('\\\\xe2\\\\x80\\\\x99s','').str.replace('\\\\xc2\\\\xa0','').str.replace('and','')
df['Investors']=df['Investors'].str.title().str.strip()

In [ ]:
df_by_investor = df.copy()
df_by_investor['Investors'] = df_by_investor['Investors'].str.split(',')
df_by_investor= df_by_investor.explode('Investors')

In [ ]:
df['Investors'].str.split(',').explode()

* The `explode()` function was applied on the investor column to separate multiple investors into individual rows for better analysis and visualization.
* The `explode()` function is used to transform list-like values in a column into separate rows.

In [ ]:
df_by_investor.sample(5)

In [ ]:
#Cleaning
df_by_investor['Investors'] = df_by_investor['Investors'].str.replace(',','').str.replace(',','').str.title().str.strip()

#### **Fixing the inconsistency in the 'Location' column -**

In [ ]:
df['Location'].unique()

In [ ]:
#Clean up known messy encoding/whitespace
df['Location'].str.replace(r'\\\\xc2\\\\xa0','',regex=True).unique()

In [ ]:
df['Location'] = df['Location'].str.replace(r'\\\\xc2\\\\xa0','',regex=True).str.strip()

In [ ]:
#Standardize delimiters to a single '/'
df['Location'] = df['Location'].replace(r'\s*(/|&|and|,|&)\s*', '/', regex=True)

In [ ]:
df['Location'].unique()

I am using a dual-dataframe approach to handle rows with multiple cities (e.g., "Mumbai / Bangalore").

**1. Why am I doing this?**
*   **To get accurate city counts:** A startup listed as "Mumbai / Bangalore" won't show up in a search for just "Mumbai." By splitting them, I can see the true activity in every city.
*   **To avoid "Money Math" errors:** Using `explode()` duplicates the row. If I'm not careful, a $10M investment will be counted twice ($10M for Mumbai + $10M for Bangalore = $20M). 

**2. The Solution:**
*   **`df` (Original):** I will use this for all **Financial Analysis** (Total/Average Funding) to ensure the dollar amounts are 100% accurate.
*   **`df_city` (Exploded):** I will use this copy for **Geographic Analysis** (City counts and maps) so that every location is represented.

In [ ]:
# Create a dedicated copy for geographic analysis
df_by_city = df.copy()

In [ ]:
#Split and Explode
df_by_city['Location'] = df_by_city['Location'].str.split('/')
df_by_city = df_by_city.explode('Location')
df_by_city['Location'].unique()

**Standardize the Location name**

In [ ]:
city_mapping = {
    # Spelling Fixes & Standardizing to common names
    'Bengaluru': 'Bangalore',
    'Gurugram': 'Gurgaon',
    'Kolkatta': 'Kolkata',
    'Ahemadabad': 'Ahmedabad',
    'Ahemdabad': 'Ahmedabad',
    'Nw Delhi': 'New Delhi',
    'Delhi': 'New Delhi',
    'Kormangala': 'Bangalore', # Neighborhood in Bangalore
    'Andheri': 'Mumbai',       # Neighborhood in Mumbai
    'Chembur': 'Mumbai',       # Neighborhood in Mumbai
    
    # State names mapped to their primary startup hubs 
    'Haryana': 'Gurgaon',
    'Karnataka': 'Bangalore',
    'Kerala': 'Kochi',
    'Uttar Pradesh': 'Noida',
    
    # Cleaning up common International/Combined labels
    'USA': 'US',
    'SFO': 'San Francisco',
    'NY': 'New York'
}

In [ ]:
df_by_city['Location'] = df_by_city['Location'].replace(city_mapping)
df_by_city['Location'].unique()

In [ ]:
df['Location'] = df['Location'].replace(city_mapping)
df['Location'].unique()